(()=>{
const $=s=>document.querySelector(s),canvas=$('#c'),ctx=canvas.getContext('2d');
let W=80,H=60,objects=[],selected=null,placeType=null,routeMode=false,connectMode=false,connectionDraft=null,route=[],view='3d',drag=null,orbitDrag=null,draft=null,routeSelection=null,routeDrag=null,obstacleDrag=null;
let yaw=-32*Math.PI/180,pitch=48*Math.PI/180,zoom=10,anim=false,progress=0,last=performance.now(),showGrid=true,showShadows=true;
const MAX_HISTORY=4;let past=[],future=[];
const colors={Vertical:'#f7f3e8',Oxer:'#f6bd60',Muro:'#e76f51',Liverpool:'#48cae4',Triple:'#90be6d',Doble:'#c77dff'};
const uid=()=> 'p3d_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);
function resize(){let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()} addEventListener('resize',resize);
function project(x,y,z=0){const r=canvas.getBoundingClientRect(),cx=r.width/2,cy=r.height/2;if(view==='top'){let s=Math.min(r.width/(W+12),r.height/(H+12))*zoom/10;return{x:cx+(x-W/2)*s,y:cy+(y-H/2)*s-z*s,s}}
 let X=x-W/2,Y=y-H/2,ca=Math.cos(yaw),sa=Math.sin(yaw),xr=X*ca-Y*sa,yr=X*sa+Y*ca,cp=Math.cos(pitch),sp=Math.sin(pitch),yp=yr*sp-z*cp,depth=yr*cp+z*sp,s=Math.min(r.width/(W+15),r.height/(H+20))*zoom/10,persp=1/(1+depth/180);return{x:cx+xr*s*persp,y:cy+yp*s*persp+25,s:s*persp,depth}}
function groundPoly(){let pts=[[0,0],[W,0],[W,H],[0,H]].map(p=>project(...p));ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='#b88f63';ctx.fill();ctx.strokeStyle='#d9b68e';ctx.lineWidth=2;ctx.stroke();if(showGrid){ctx.save();ctx.strokeStyle='#ffffff18';ctx.lineWidth=1;for(let x=0;x<=W;x+=5){let a=project(x,0),b=project(x,H);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let y=0;y<=H;y+=5){let a=project(0,y),b=project(W,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}}
function drawJump(o){let p=project(o.x,o.y,0),rad=o.rot*Math.PI/180,dx=Math.cos(rad)*o.width/2,dy=Math.sin(rad)*o.width/2,a=project(o.x-dx,o.y-dy,0),b=project(o.x+dx,o.y+dy,0),at=project(o.x-dx,o.y-dy,o.height),bt=project(o.x+dx,o.y+dy,o.height);if(showShadows&&view==='3d'){ctx.strokeStyle='#0004';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(a.x+8,a.y+5);ctx.lineTo(b.x+8,b.y+5);ctx.stroke()}ctx.strokeStyle=colors[o.type]||'#fff';ctx.lineWidth=Math.max(3,p.s*.22);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(at.x,at.y);ctx.moveTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.stroke();if(o.type==='Oxer'||o.type==='Triple'||o.type==='Doble'){let off=.9,px=-Math.sin(rad)*off,py=Math.cos(rad)*off,c=project(o.x-dx+px,o.y-dy+py,o.height*.85),d=project(o.x+dx+px,o.y+dy+py,o.height*.85);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}if(o.type==='Muro'){ctx.fillStyle=colors[o.type]+'bb';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(at.x,at.y);ctx.closePath();ctx.fill()}if(o.type==='Liverpool'){ctx.fillStyle='#249dd0aa';let rr=Math.max(8,p.s*1.1);ctx.fillRect(p.x-rr,p.y-rr*.3,rr*2,rr*.6)}ctx.fillStyle=o===selected?'#ffd166':'#07111f';ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y-16,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=o===selected?'#07111f':'#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.num||'?',p.x,p.y-16);if(o===selected){ctx.strokeStyle='#ffd166';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.stroke()}}
function drawObstacleHandles(){if(!selected)return;let o=selected,p=project(o.x,o.y,.25),rad=o.rot*Math.PI/180,sz=project(o.x+Math.cos(rad)*o.width/2,o.y+Math.sin(rad)*o.width/2,.25),rot=project(o.x,o.y-4,.25),ht=project(o.x,o.y,o.height+.8);ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle='#ffd166aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(sz.x,sz.y);ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.moveTo(p.x,p.y);ctx.lineTo(ht.x,ht.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#39bdf8';ctx.strokeStyle='#07111f';ctx.beginPath();ctx.arc(rot.x,rot.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd166';ctx.fillRect(sz.x-7,sz.y-7,14,14);ctx.strokeRect(sz.x-7,sz.y-7,14,14);ctx.fillStyle='#ff6b6b';ctx.beginPath();ctx.arc(ht.x,ht.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function connectorPoints(o){let r=o.rot*Math.PI/180,dx=Math.cos(r)*o.width/2,dy=Math.sin(r)*o.width/2;return[{x:o.x-dx,y:o.y-dy},{x:o.x+dx,y:o.y+dy}]}
function connectionExists(a,b){return route.some(n=>n.kind==='connection'&&((n.fromObstacleId===a.id&&n.toObstacleId===b.id)||(n.fromObstacleId===b.id&&n.toObstacleId===a.id)))}
function obstacleNode(o){return route.find(n=>n.kind==='obstacle'&&n.objectId===o.id)}
function drawConnectors(){if(!connectMode||!selected)return;objects.forEach(o=>{if(o===selected)return;let q=project(o.x,o.y,.38),valid=!connectionExists(selected,o),hover=connectionDraft&&hit(q.x,q.y)===o;ctx.save();ctx.strokeStyle=hover?'#fff':valid?'#57e389':'#ff6b6b';ctx.lineWidth=hover?4:2;ctx.setLineDash(hover?[2,2]:[6,4]);ctx.beginPath();ctx.arc(q.x,q.y,22,0,Math.PI*2);ctx.stroke();ctx.restore()});let pts=connectorPoints(selected);pts.forEach((p,i)=>{let q=project(p.x,p.y,.35);ctx.fillStyle=i?'#57e389':'#39bdf8';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#07111f';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i?'S':'E',q.x,q.y)});if(connectionDraft){let a=project(connectionDraft.start.x,connectionDraft.start.y,.35),b=pointerPos(connectionDraft.event);ctx.strokeStyle=hit(b.x,b.y)&&hit(b.x,b.y)!==selected&&!connectionExists(selected,hit(b.x,b.y))?'#57e389':'#ff6b6b';ctx.lineWidth=4;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([])}}
function nodePoints(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return[{x:o?o.x:n.x,y:o?o.y:n.y}]}if(n.kind==='line')return[n.a,n.b];if(n.kind==='curve'||n.kind==='connection')return n.points||[];if(n.kind==='circle'){let a=[];for(let i=0;i<=24;i++){let t=i/24*Math.PI*2;a.push({x:n.cx+Math.cos(t)*n.r,y:n.cy+Math.sin(t)*n.r})}return a}return[{x:n.x,y:n.y}]}
function isCourseNode(n){return n.kind==='obstacle'||n.kind==='point'||n.kind==='connection'}
function allRoutePoints(){return route.filter(isCourseNode).flatMap(n=>n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n))}
function catmull(points,steps=14){if(points.length<2)return points;let out=[];for(let i=0;i<points.length-1;i++){let p0=points[Math.max(0,i-1)],p1=points[i],p2=points[i+1],p3=points[Math.min(points.length-1,i+2)];for(let j=0;j<steps;j++){let t=j/steps,t2=t*t,t3=t2*t;out.push({x:.5*((2*p1.x)+(-p0.x+p2.x)*t+(2*p0.x-5*p1.x+4*p2.x-p3.x)*t2+(-p0.x+3*p1.x-3*p2.x+p3.x)*t3),y:.5*((2*p1.y)+(-p0.y+p2.y)*t+(2*p0.y-5*p1.y+4*p2.y-p3.y)*t2+(-p0.y+3*p1.y-3*p2.y+p3.y)*t3)})}}out.push(points.at(-1));return out}
function arrow(a,b,color='#ffd166'){let p=project(b.x,b.y,.12),q=project(a.x,a.y,.12),ang=Math.atan2(p.y-q.y,p.x-q.x);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(ang);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-7);ctx.lineTo(-5,0);ctx.lineTo(-8,7);ctx.closePath();ctx.fill();ctx.restore()}
function drawRouteGeometry(){route.forEach(n=>{if(n.kind==='line'||n.kind==='curve'||n.kind==='connection'){let base=nodePoints(n),shape=n.kind==='line'?base:catmull(base,18),pts=shape.map(p=>project(p.x,p.y,.1));ctx.strokeStyle=n.kind==='connection'?'#57e389':(n.arrow?'#ffd166':'#8de1ff');ctx.lineWidth=n.kind==='connection'?5:4;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();if(n.arrow||n.kind==='connection'){let end=shape.at(-1),prev=shape[Math.max(0,shape.length-2)];arrow(prev,end,n.kind==='connection'?'#57e389':'#ffd166')}}if(n.kind==='circle'){let pts=nodePoints(n).map(p=>project(p.x,p.y,.1));ctx.strokeStyle='#ffd166';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}})}
function drawRouteHandles(){if(!routeSelection)return;let pts=nodePoints(routeSelection);ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#ffd16688';ctx.lineWidth=2;if(routeSelection.kind==='circle'){let c=project(routeSelection.cx,routeSelection.cy,.2),r=project(routeSelection.cx+routeSelection.r,routeSelection.cy,.2);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(r.x,r.y);ctx.stroke()}else if(pts.length>1){ctx.beginPath();pts.forEach((p,i)=>{let q=project(p.x,p.y,.2);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}ctx.setLineDash([]);pts.forEach(p=>{let q=project(p.x,p.y,.22);ctx.fillStyle='#ffd166';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore()}
function drawMarkers(){route.forEach(n=>{if(n.kind!=='point')return;let p=project(n.x,n.y,.15);ctx.fillStyle=n.marker==='start'?'#57e389':'#ff6b6b';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#07111f';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(n.marker==='start'?'S':'L',p.x,p.y)})}
function drawRoute(){let raw=allRoutePoints(),pts=catmull(raw).map(p=>project(p.x,p.y,.16));if(pts.length>1){ctx.strokeStyle='#e8f5ff99';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();let n=Math.max(2,Math.floor(pts.length*(anim?progress:1)));ctx.strokeStyle='#ef476f';ctx.shadowColor='#ef476f';ctx.shadowBlur=12;ctx.lineWidth=8;ctx.beginPath();pts.slice(0,n).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=0;if(n>2){let k=Math.min(raw.length-1,Math.max(1,Math.floor(n/14)));arrow(raw[k-1],raw[k],'#ffd166')}}}
function draw(){let r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);let g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,'#8fc5df');g.addColorStop(.45,'#d7e7e8');g.addColorStop(.46,'#365d3e');g.addColorStop(1,'#17311f');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);groundPoly();drawRouteGeometry();drawRoute();drawMarkers();drawRouteHandles();[...objects].sort((a,b)=>(project(a.x,a.y).depth||0)-(project(b.x,b.y).depth||0)).forEach(drawJump);drawObstacleHandles();drawConnectors();if(draft){let p=project(draft.points?draft.points.at(-1).x:draft.start.x,draft.points?draft.points.at(-1).y:draft.start.y,.2);ctx.strokeStyle='#ffd166';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.stroke()}}
function unproject(sx,sy){let r=canvas.getBoundingClientRect();if(view==='top'){let s=Math.min(r.width/(W+12),r.height/(H+12))*zoom/10;return{x:(sx-r.width/2)/s+W/2,y:(sy-r.height/2)/s+H/2}}let o=project(0,0),px=project(1,0),py=project(0,1),ax=px.x-o.x,ay=px.y-o.y,bx=py.x-o.x,by=py.y-o.y,dx=sx-o.x,dy=sy-o.y,det=ax*by-ay*bx;return{x:(dx*by-dy*bx)/det,y:(ax*dy-ay*dx)/det}}
function hit(sx,sy){let best=null,bd=28;objects.forEach(o=>{let p=project(o.x,o.y),d=Math.hypot(p.x-sx,p.y-sy);if(d<bd){best=o;bd=d}});return best}function hitObstacleHandle(sx,sy){if(!selected)return null;let o=selected,rad=o.rot*Math.PI/180,p=project(o.x,o.y,.25),sz=project(o.x+Math.cos(rad)*o.width/2,o.y+Math.sin(rad)*o.width/2,.25),rot=project(o.x,o.y-4,.25);if(Math.hypot(rot.x-sx,rot.y-sy)<18)return'rotate';if(Math.hypot(sz.x-sx,sz.y-sy)<18)return'size';return null}function hitRouteHandle(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i];if(n.kind==='circle'){let q=project(n.cx+n.r,n.cy,.2);if(Math.hypot(q.x-sx,q.y-sy)<16)return{node:n,index:'radius'}}let pts=nodePoints(n);for(let j=0;j<pts.length;j++){let q=project(pts[j].x,pts[j].y,.2);if(Math.hypot(q.x-sx,q.y-sy)<16)return{node:n,index:j}}}return null}function segmentDistance(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,t=((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}function hitRouteGeometry(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i],pts=n.kind==='curve'||n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n);if(n.kind==='circle'){let q=project(n.cx,n.cy,.1),r=project(n.cx+n.r,n.cy,.1).x-q.x;if(Math.abs(Math.hypot(sx-q.x,sy-q.y)-Math.abs(r))<14)return n;continue}for(let j=1;j<pts.length;j++){let a=project(pts[j-1].x,pts[j-1].y,.1),b=project(pts[j].x,pts[j].y,.1);if(segmentDistance({x:sx,y:sy},a,b)<12)return n}}return null}function pointerPos(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function snapshot(){return JSON.stringify({W,H,objects,route})}function restore(s){let d=JSON.parse(s);W=d.W;H=d.H;objects=d.objects||[];route=d.route||[];routeSelection=null;routeDrag=null;$('#arenaW').value=W;$('#arenaH').value=H;selected=selected&&objects.find(o=>o.id===selected.id)||null;updateUI();draw()}
function history(){past.push(snapshot());if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}function buttons(){$('#undo').disabled=!past.length;$('#redo').disabled=!future.length}function undo(){if(!past.length)return;future.push(snapshot());restore(past.pop())}function redo(){if(!future.length)return;past.push(snapshot());restore(future.pop())}
function addObject(type,x=W/2,y=H/2){history();let o={id:uid(),type,x,y,rot:0,height:type==='Muro'?1.5:1.4,width:type==='Oxer'?2:1.8,num:String(objects.length+1)};objects.push(o);selected=o;updateUI();draw()}function addMarker(marker,x,y){history();route.push({id:uid(),kind:'point',marker,x:Math.max(0,Math.min(W,x)),y:Math.max(0,Math.min(H,y))});placeType=null;setMode('seleccionar');updateUI();draw()}
function setMode(s){$('#modePill').textContent='Modo: '+s}function updateInspector(){let on=!!selected;$('#inspector').style.display=on?'block':'none';$('#emptyInspector').style.display=on?'none':'block';if(!on)return;$('#iType').value=selected.type;$('#iNum').value=selected.num;$('#iRot').value=selected.rot;$('#iHeight').value=selected.height;$('#iWidth').value=selected.width}
function routeLabel(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return o?o.num+' · '+o.type:'Punto fijado'}if(n.kind==='point')return n.marker==='start'?'Salida':'Llegada';if(n.kind==='circle')return'Círculo';if(n.kind==='connection')return'Tramo conectado';if(n.kind==='curve')return'Curva editable';return n.arrow?'Línea con flecha':'Línea recta'}function updateUI(){W=+$ ('#arenaW').value||80;H=+$('#arenaH').value||60;$('#countPill').textContent=objects.length+' obstáculos';updateInspector();let box=$('#routeList');box.innerHTML='';route.forEach((n,i)=>{let d=document.createElement('div');d.className='item';d.dataset.routeIndex=i;d.innerHTML=`<span class="badge">${i+1}</span><span>${routeLabel(n)}</span>`;d.onclick=()=>{routeSelection=n;selected=null;updateUI();draw()};if(n===routeSelection)d.classList.add('active');box.appendChild(d)});$('#addRoutePoint').disabled=!routeSelection||!['line','curve','connection'].includes(routeSelection.kind);let ri=routeSelection?route.indexOf(routeSelection):-1;$('#moveRouteUp').disabled=ri<=0;$('#moveRouteDown').disabled=ri<0||ri>=route.length-1;buttons()}
document.querySelectorAll('.jump[data-type]').forEach(b=>b.onclick=()=>{placeType=b.dataset.type;routeMode=false;$('#routeMode').classList.remove('active');setMode('colocar '+placeType);$('#leftPanel').classList.remove('show')});document.querySelectorAll('.routeTool').forEach(b=>b.onclick=()=>{placeType=b.dataset.tool;routeMode=false;draft=null;$('#routeMode').classList.remove('active');setMode('colocar '+b.dataset.tool);$('#leftPanel').classList.remove('show')});
$('#routeMode').onclick=()=>{routeMode=!routeMode;placeType=null;draft=null;$('#routeMode').classList.toggle('active',routeMode);setMode(routeMode?'definir recorrido':'seleccionar')};$('#clearRoute').onclick=()=>{if(route.length){history();route=[];routeSelection=null;updateUI();draw()}};$('#addRoutePoint').onclick=()=>{if(!routeSelection||!['line','curve'].includes(routeSelection.kind))return;let pts=routeSelection.kind==='line'?[routeSelection.a,routeSelection.b]:routeSelection.points;if(pts.length<2)return;let best=1,dist=-1;for(let i=1;i<pts.length;i++){let d=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);if(d>dist){dist=d;best=i}}let a=pts[best-1],b=pts[best],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};history();if(routeSelection.kind==='line'){routeSelection={...routeSelection,kind:'curve',points:[a,mid,b]};route[route.indexOf(route.find(n=>n.id===routeSelection.id))]=routeSelection}else routeSelection.points.splice(best,0,mid);updateUI();draw()};function moveRoute(delta){let i=routeSelection?route.indexOf(routeSelection):-1,j=i+delta;if(i<0||j<0||j>=route.length)return;history();[route[i],route[j]]=[route[j],route[i]];updateUI();draw()}$('#moveRouteUp').onclick=()=>moveRoute(-1);$('#moveRouteDown').onclick=()=>moveRoute(1);$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#viewTop').onclick=()=>{view='top';$('#camPill').textContent='Cámara: cenital';draw()};$('#view3d').onclick=()=>{view='3d';$('#camPill').textContent='Cámara: 3D';draw()};$('#play').onclick=()=>{if(allRoutePoints().length<2){status('Define al menos 2 elementos en el recorrido');return}anim=!anim;progress=anim?0:1;$('#play').textContent=anim?'⏸ Pausar':'▶ Recorrido'};function status(t){$('#status').textContent='● '+t;setTimeout(()=>$('#status').textContent='● JavaScript ACTIVO',2200)}
function hitConnector(sx,sy){if(!connectMode||!selected)return null;let pts=connectorPoints(selected);for(let i=0;i<pts.length;i++){let q=project(pts[i].x,pts[i].y,.35);if(Math.hypot(q.x-sx,q.y-sy)<20)return{index:i,point:pts[i]}}return null}function hitObstacleHeight(sx,sy){if(!selected)return false;let q=project(selected.x,selected.y,selected.height+.8);return Math.hypot(q.x-sx,q.y-sy)<18}
canvas.addEventListener('pointerdown',e=>{if(!connectMode)return;let q=pointerPos(e),c=hitConnector(q.x,q.y);if(!c)return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);connectionDraft={from:selected,start:c.point,event:e};setMode('arrastra al obstáculo de destino');draw()});canvas.addEventListener('pointermove',e=>{if(!connectionDraft)return;e.stopImmediatePropagation();connectionDraft.event=e;draw()});canvas.addEventListener('pointerup',e=>{if(!connectionDraft)return;e.stopImmediatePropagation();let q=pointerPos(e),target=hit(q.x,q.y),from=connectionDraft.from;if(target&&target!==from){let duplicate=route.some(n=>n.kind==='connection'&&((n.fromObstacleId===from.id&&n.toObstacleId===target.id)||(n.fromObstacleId===target.id&&n.toObstacleId===from.id)));if(!duplicate){let end=connectorPoints(target)[connectionDraft.start.x<from.x?1:0];history();let n={id:uid(),kind:'connection',points:[connectionDraft.start,{x:(connectionDraft.start.x+end.x)/2,y:(connectionDraft.start.y+end.y)/2},end],fromObstacleId:from.id,toObstacleId:target.id};route.push(n);routeSelection=n;selected=target;status('Tramo conectado')}else status('Ese tramo ya existe')}connectionDraft=null;setMode('seleccionar');updateUI();draw()});canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e);if(!hitObstacleHeight(q.x,q.y))return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);obstacleDrag={kind:'height',o:selected,before:snapshot(),startY:e.clientY,startHeight:selected.height};draw()});
canvas.addEventListener('pointermove',e=>{if(!obstacleDrag||obstacleDrag.kind!=='height')return;e.stopImmediatePropagation();let scale=Math.max(8,Math.abs(project(obstacleDrag.o.x,obstacleDrag.o.y,1).y-project(obstacleDrag.o.x,obstacleDrag.o.y,0).y));obstacleDrag.o.height=Math.max(.4,Math.min(4,obstacleDrag.startHeight+(obstacleDrag.startY-e.clientY)/scale));draw()});
canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e),kind=hitObstacleHandle(q.x,q.y);if(!kind)return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);obstacleDrag={kind,o:selected,before:snapshot()};draw()});
canvas.addEventListener('pointermove',e=>{if(!obstacleDrag)return;e.stopImmediatePropagation();let q=pointerPos(e),p=unproject(q.x,q.y),o=obstacleDrag.o;if(obstacleDrag.kind==='rotate')o.rot=Math.round(Math.atan2(p.y-o.y,p.x-o.x)*180/Math.PI);else o.width=Math.max(.8,Math.min(12,Math.hypot(p.x-o.x,p.y-o.y)*2));draw()});
canvas.addEventListener('pointerup',e=>{if(!obstacleDrag)return;e.stopImmediatePropagation();past.push(obstacleDrag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons();obstacleDrag=null;updateInspector();draw()});
canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e),n=hitRouteGeometry(q.x,q.y);if(!n)return;e.stopImmediatePropagation();routeSelection=n;selected=null;updateUI();draw()});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);let q=pointerPos(e),h=hit(q.x,q.y),p=unproject(q.x,q.y);if(placeType==='start'||placeType==='finish'){addMarker(placeType,p.x,p.y);return}if(placeType==='curve'){if(!draft){draft={tool:'curve',points:[p]};setMode('añade puntos; doble toque para terminar')}else draft.points.push(p);draw();return}if(placeType==='line'||placeType==='lineArrow'||placeType==='circle'){if(!draft){draft={tool:placeType,start:p};setMode('marca el segundo punto');draw();return}history();let n;if(placeType==='circle')n={id:uid(),kind:'circle',cx:draft.start.x,cy:draft.start.y,r:Math.max(1,Math.hypot(p.x-draft.start.x,p.y-draft.start.y))};else n={id:uid(),kind:'line',a:draft.start,b:p,arrow:placeType==='lineArrow'};route.push(n);routeSelection=n;draft=null;placeType=null;setMode('seleccionar');updateUI();draw();return}if(placeType){addObject(placeType,p.x,p.y);placeType=null;setMode('seleccionar');return}let rh=hitRouteHandle(q.x,q.y);if(rh){routeSelection=rh.node;routeDrag={node:rh.node,index:rh.index,before:snapshot()};draw();return}if(routeMode&&h){if(!route.some(n=>n.kind==='obstacle'&&n.objectId===h.id)){history();route.push({id:uid(),kind:'obstacle',objectId:h.id,x:h.x,y:h.y});updateUI();draw()}return}if(h){selected=h;routeSelection=null;drag={o:h,before:snapshot(),moved:false};updateUI();draw()}else if(view==='3d')orbitDrag={x:e.clientX,y:e.clientY,yaw,pitch}});
canvas.addEventListener('pointermove',e=>{let q=pointerPos(e),p=unproject(q.x,q.y);if(routeDrag){let n=routeDrag.node;if(routeDrag.index==='radius')n.r=Math.max(1,Math.min(40,Math.hypot(p.x-n.cx,p.y-n.cy)));else if(n.kind==='circle'){n.cx=p.x;n.cy=p.y}else if(n.kind==='curve')n.points[routeDrag.index]={x:p.x,y:p.y};else if(n.kind==='line'){let k=routeDrag.index?'b':'a';n[k]={x:p.x,y:p.y}}draw()}else if(drag){drag.o.x=Math.max(0,Math.min(W,p.x));drag.o.y=Math.max(0,Math.min(H,p.y));drag.moved=true;draw()}else if(orbitDrag){yaw=orbitDrag.yaw+(e.clientX-orbitDrag.x)*.008;pitch=Math.max(.2,Math.min(1.35,orbitDrag.pitch+(e.clientY-orbitDrag.y)*.006));$('#yaw').value=yaw*180/Math.PI;$('#pitch').value=pitch*180/Math.PI;draw()}});canvas.addEventListener('pointerup',()=>{if(routeDrag){past.push(routeDrag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}if(drag?.moved){past.push(drag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}routeDrag=null;drag=null;orbitDrag=null;updateInspector()});canvas.addEventListener('dblclick',()=>{if(placeType==='curve'&&draft?.points?.length>=2){history();let n={id:uid(),kind:'curve',points:draft.points.slice()};route.push(n);routeSelection=n;draft=null;placeType=null;setMode('seleccionar');updateUI();draw()}});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(5,Math.min(18,zoom-e.deltaY*.01));$('#zoom').value=zoom;draw()},{passive:false});
[['arenaW','W'],['arenaH','H']].forEach(([id,k])=>$('#'+id).onchange=()=>{history();updateUI();draw()});[['iType','type'],['iNum','num'],['iRot','rot'],['iHeight','height'],['iWidth','width']].forEach(([id,k])=>$('#'+id).onchange=e=>{if(selected){history();selected[k]=(k==='type'||k==='num')?e.target.value:+e.target.value;updateUI();draw()}});
$('#delete').onclick=()=>{if(!selected)return;history();route=route.map(n=>n.kind==='obstacle'&&n.objectId===selected.id?{...n,kind:'point',objectId:null,x:selected.x,y:selected.y}:n);objects=objects.filter(o=>o!==selected);selected=null;updateUI();draw()};$('#duplicate').onclick=()=>{if(!selected)return;history();let o={...selected,id:uid(),x:selected.x+3,y:selected.y+3,num:String(objects.length+1)};objects.push(o);selected=o;updateUI();draw()};
$('#pitch').oninput=e=>{pitch=+e.target.value*Math.PI/180;draw()};$('#yaw').oninput=e=>{yaw=+e.target.value*Math.PI/180;draw()};$('#zoom').oninput=e=>{zoom=+e.target.value;draw()};$('#grid').onchange=e=>{showGrid=e.target.checked;draw()};$('#shadows').onchange=e=>{showShadows=e.target.checked;draw()};
$('#saveBtn').onclick=()=>{let data={version:'0.4',arena:{width:W,length:H},objects,route};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='faas_equestrian_course.json';a.click();URL.revokeObjectURL(a.href);status('Proyecto guardado')};$('#exportPng').onclick=()=>{draw();canvas.toBlob(blob=>{if(!blob){status('No se pudo exportar la imagen');return}let a=document.createElement('a'),stamp=new Date().toISOString().slice(0,10);a.href=URL.createObjectURL(blob);a.download=`faas_equestrian_course_${stamp}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('Diseño PNG exportado')},'image/png')};$('#loadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());objects=data.objects||[];route=(data.route||[]).map(n=>typeof n==='string'?{id:uid(),kind:'obstacle',objectId:n,x:objects.find(o=>o.id===n)?.x||0,y:objects.find(o=>o.id===n)?.y||0}:n);W=data.arena?.width||80;H=data.arena?.length||60;$('#arenaW').value=W;$('#arenaH').value=H;selected=null;updateUI();draw();status('Proyecto abierto')}catch{status('No se pudo abrir el JSON')}};
$('#demoBtn').onclick=()=>{history();objects=[];route=[];let demo=[['Vertical',12,16,20],['Oxer',27,10,-15],['Vertical',43,18,40],['Doble',61,12,85],['Muro',67,34,10],['Oxer',48,47,-30],['Liverpool',27,42,70],['Triple',12,49,5]];demo.forEach((d,i)=>{let o={id:uid(),type:d[0],x:d[1],y:d[2],rot:d[3],height:d[0]==='Muro'?1.5:1.4,width:d[0]==='Oxer'?2:1.8,num:String(i+1)};objects.push(o);route.push({id:uid(),kind:'obstacle',objectId:o.id,x:o.x,y:o.y})});selected=null;updateUI();draw();status('Demo cargada')};$('#leftToggle').onclick=()=>$('#leftPanel').classList.toggle('show');$('#rightToggle').onclick=()=>$('#rightPanel').classList.toggle('show');
$('#connectMode').onclick=()=>{connectMode=!connectMode;routeMode=false;placeType=null;draft=null;connectionDraft=null;$('#connectMode').classList.toggle('active',connectMode);$('#routeMode').classList.remove('active');setMode(connectMode?'selecciona un obstáculo y arrastra desde E/S':'seleccionar');draw()};$('#routeMode').addEventListener('click',()=>{connectMode=false;connectionDraft=null;$('#connectMode').classList.remove('active')});document.querySelectorAll('.routeTool').forEach(b=>b.addEventListener('click',()=>{connectMode=false;connectionDraft=null;$('#connectMode').classList.remove('active')}));
function tick(t){let dt=(t-last)/1000;last=t;if(anim){progress+=dt/7;if(progress>=1){progress=1;anim=false;$('#play').textContent='▶ Recorrido'}draw()}requestAnimationFrame(tick)}resize();updateUI();$('#status').textContent='● JavaScript ACTIVO';requestAnimationFrame(tick);
function courseDistance(){let pts=allRoutePoints(),m=0;for(let i=1;i<pts.length;i++)m+=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);return m}
function updateMetrics(){let m=courseDistance(),stride=Math.max(2,+$('#strideLength').value||3.5),steps=m?Math.round(m/stride):0;$('#courseMetrics').textContent=`Distancia: ${m.toFixed(1)} m · Trancos estimados: ${steps}`}
function validateCourse(){let nodes=route.filter(n=>n.kind==='obstacle'),start=route.some(n=>n.kind==='point'&&n.marker==='start'),finish=route.some(n=>n.kind==='point'&&n.marker==='finish'),missing=objects.filter(o=>!obstacleNode(o));let messages=[];if(!start)messages.push('falta Salida');if(!finish)messages.push('falta Llegada');if(!nodes.length)messages.push('no hay obstáculos en el recorrido');if(missing.length)messages.push(missing.length+' obstáculo(s) sin ordenar');let ok=!messages.length;updateMetrics();$('#validation').textContent=ok?'✓ Recorrido básico completo: salida, llegada y obstáculos incorporados.':'⚠ '+messages.join(' · ');$('#validation').style.color=ok?'#57e389':'#ffd166';status(ok?'Recorrido válido':'Revisa el recorrido')}
function autoOrder(){let nodes=route.filter(n=>n.kind==='obstacle'),links=route.filter(n=>n.kind==='connection');if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),nearest=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],current=start?nearest(start):nodes[0],ordered=[],used=new Set;while(current&&!used.has(current.objectId)){ordered.push(current);used.add(current.objectId);let link=links.find(n=>n.fromObstacleId===current.objectId&&!used.has(n.toObstacleId));current=link?nodes.find(n=>n.objectId===link.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],link=next&&links.find(l=>l.fromObstacleId===n.objectId&&l.toObstacleId===next.objectId);if(link)course.push(link)});if(start)course.unshift(start);if(finish)course.push(finish);let graphics=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...graphics];routeSelection=null;ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o)o.num=String(i+1)});updateUI();draw();status('Recorrido ordenado')}
$('#autoOrder').onclick=autoOrder;$('#validateCourse').onclick=validateCourse;$('#strideLength').oninput=updateMetrics;
function courseObstacleNodes(){let ns=route.filter(n=>n.kind==='obstacle');route.filter(n=>n.kind==='connection').forEach(c=>[c.fromObstacleId,c.toObstacleId].forEach(id=>{let o=objects.find(x=>x.id===id);if(o&&!ns.some(n=>n.objectId===id))ns.push({id:uid(),kind:'obstacle',objectId:id,x:o.x,y:o.y})}));return ns}
function autoOrder(){let nodes=courseObstacleNodes(),links=route.filter(n=>n.kind==='connection');if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),near=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],cur=start?near(start):nodes[0],ordered=[],used=new Set;while(cur&&!used.has(cur.objectId)){ordered.push(cur);used.add(cur.objectId);let l=links.find(n=>n.fromObstacleId===cur.objectId&&!used.has(n.toObstacleId));cur=l?nodes.find(n=>n.objectId===l.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],l=next&&links.find(x=>x.fromObstacleId===n.objectId&&x.toObstacleId===next.objectId);if(l)course.push(l)});if(start)course.unshift(start);if(finish)course.push(finish);let graphics=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...graphics];ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o)o.num=String(i+1)});routeSelection=null;updateUI();draw();status('Recorrido ordenado')}
function deleteSelectedObstacle(){if(!selected)return;history();let o=selected;route=route.map(n=>n.kind==='obstacle'&&n.objectId===o.id?{...n,kind:'obstacle',objectId:null,x:o.x,y:o.y}:n);route.forEach(n=>{if(n.kind==='connection'&&(n.fromObstacleId===o.id||n.toObstacleId===o.id))n.detached=true});objects=objects.filter(x=>x!==o);selected=null;routeSelection=null;updateUI();draw()}
$('#delete').onclick=deleteSelectedObstacle;
function syncConnections(){route.filter(n=>n.kind==='connection'&&n.points?.length>=2).forEach(n=>{let from=objects.find(o=>o.id===n.fromObstacleId),to=objects.find(o=>o.id===n.toObstacleId);if(from){let ps=connectorPoints(from),p=n.points[0],q=ps.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];n.points[0]={...q}}if(to){let ps=connectorPoints(to),p=n.points.at(-1),q=ps.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];n.points[n.points.length-1]={...q}}})}
function nodePoints(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return[{x:o?o.x:n.x,y:o?o.y:n.y}]}if(n.kind==='line')return[n.a,n.b];if(n.kind==='curve'||n.kind==='connection'){if(n.kind==='connection')syncConnections();return n.points||[]}if(n.kind==='circle'){let a=[];for(let i=0;i<=24;i++){let t=i/24*Math.PI*2;a.push({x:n.cx+Math.cos(t)*n.r,y:n.cy+Math.sin(t)*n.r})}return a}return[{x:n.x,y:n.y}]}
canvas.addEventListener('pointerdown',e=>{let q=pointerPos(e),n=hitRouteGeometry(q.x,q.y);if(!n||!['line','curve','connection'].includes(n.kind))return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);routeSelection=n;selected=null;routeDrag={node:n,index:'move',before:snapshot(),start:unproject(q.x,q.y),original:nodePoints(n).map(p=>({...p}))};updateUI();draw()},true);
canvas.addEventListener('pointermove',e=>{if(!routeDrag||routeDrag.index!=='move')return;e.stopImmediatePropagation();let q=pointerPos(e),p=unproject(q.x,q.y),dx=p.x-routeDrag.start.x,dy=p.y-routeDrag.start.y,n=routeDrag.node;if(n.kind==='line'){n.a={x:routeDrag.original[0].x+dx,y:routeDrag.original[0].y+dy};n.b={x:routeDrag.original[1].x+dx,y:routeDrag.original[1].y+dy}}else n.points=routeDrag.original.map(v=>({x:v.x+dx,y:v.y+dy}));draw()},true);
})();
