(()=>{
const $=s=>document.querySelector(s),canvas=$('#c'),ctx=canvas.getContext('2d');
let W=80,H=60,objects=[],assets=[],sceneRefs=[],sceneObjects=[],selectedScene=null,sceneDrag=null,selected=null,placeType=null,routeMode=false,connectMode=false,connectionDraft=null,route=[],view='3d',drag=null,orbitDrag=null,draft=null,routeSelection=null,routeDrag=null,obstacleDrag=null,logoImages={};
let yaw=-32*Math.PI/180,pitch=48*Math.PI/180,zoom=10,anim=false,progress=0,last=performance.now(),showGrid=true,showShadows=true;
let geometryConnectMode=false,geometryConnectSource=null,executionQueue=[],executionIndex=0,executionProgress=0,executionRunning=false;
let executionSpeed=1,executionColor='#ef476f',executionWidth=8,executionDash='solid';
const MAX_HISTORY=4;let past=[],future=[];
const colors={Vertical:'#f7f3e8',Oxer:'#f6bd60',Muro:'#e76f51',Liverpool:'#48cae4',Triple:'#90be6d',Doble:'#c77dff'};
const uid=()=> 'p3d_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2);
function resize(){let r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);draw()} addEventListener('resize',resize);
function project(x,y,z=0){const r=canvas.getBoundingClientRect(),cx=r.width/2,cy=r.height/2;if(view==='top'){let s=Math.min(r.width/(W+12),r.height/(H+12))*zoom/10;return{x:cx+(x-W/2)*s,y:cy+(y-H/2)*s-z*s,s}}
 let X=x-W/2,Y=y-H/2,ca=Math.cos(yaw),sa=Math.sin(yaw),xr=X*ca-Y*sa,yr=X*sa+Y*ca,cp=Math.cos(pitch),sp=Math.sin(pitch),yp=yr*sp-z*cp,depth=yr*cp+z*sp,s=Math.min(r.width/(W+15),r.height/(H+20))*zoom/10,persp=1/(1+depth/180);return{x:cx+xr*s*persp,y:cy+yp*s*persp+25,s:s*persp,depth}}
function groundPoly(){let pts=[[0,0],[W,0],[W,H],[0,H]].map(p=>project(...p));ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='#b88f63';ctx.fill();ctx.strokeStyle='#d9b68e';ctx.lineWidth=2;ctx.stroke();if(showGrid){ctx.save();ctx.strokeStyle='#ffffff18';ctx.lineWidth=1;for(let x=0;x<=W;x+=5){let a=project(x,0),b=project(x,H);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let y=0;y<=H;y+=5){let a=project(0,y),b=project(W,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}ctx.restore()}}
function drawJump(o){let p=project(o.x,o.y,0),rad=o.rot*Math.PI/180,dx=Math.cos(rad)*o.width/2,dy=Math.sin(rad)*o.width/2,a=project(o.x-dx,o.y-dy,0),b=project(o.x+dx,o.y+dy,0),at=project(o.x-dx,o.y-dy,o.height),bt=project(o.x+dx,o.y+dy,o.height);if(showShadows&&view==='3d'){ctx.strokeStyle='#0004';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(a.x+8,a.y+5);ctx.lineTo(b.x+8,b.y+5);ctx.stroke()}ctx.strokeStyle=colors[o.type]||'#fff';ctx.lineWidth=Math.max(3,p.s*.22);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(at.x,at.y);ctx.moveTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.stroke();if(o.type==='Oxer'||o.type==='Triple'||o.type==='Doble'){let off=.9,px=-Math.sin(rad)*off,py=Math.cos(rad)*off,c=project(o.x-dx+px,o.y-dy+py,o.height*.85),d=project(o.x+dx+px,o.y+dy+py,o.height*.85);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}if(o.type==='Muro'){ctx.fillStyle=colors[o.type]+'bb';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(at.x,at.y);ctx.closePath();ctx.fill()}if(o.type==='Liverpool'){ctx.fillStyle='#249dd0aa';let rr=Math.max(8,p.s*1.1);ctx.fillRect(p.x-rr,p.y-rr*.3,rr*2,rr*.6)}ctx.fillStyle=o===selected?'#ffd166':'#07111f';ctx.strokeStyle='#fff';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y-16,11,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle=o===selected?'#07111f':'#fff';ctx.font='bold 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.num||'?',p.x,p.y-16);if(o===selected){ctx.strokeStyle='#ffd166';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,18,0,Math.PI*2);ctx.stroke()}}
function drawObstacleHandles(){if(!selected)return;let o=selected,p=project(o.x,o.y,.25),rad=o.rot*Math.PI/180,sz=project(o.x+Math.cos(rad)*o.width/2,o.y+Math.sin(rad)*o.width/2,.25),rot=project(o.x,o.y-4,.25),ht=project(o.x,o.y,o.height+.8);ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle='#ffd166aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(sz.x,sz.y);ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.moveTo(p.x,p.y);ctx.lineTo(ht.x,ht.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#39bdf8';ctx.strokeStyle='#07111f';ctx.beginPath();ctx.arc(rot.x,rot.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd166';ctx.fillRect(sz.x-7,sz.y-7,14,14);ctx.strokeRect(sz.x-7,sz.y-7,14,14);ctx.fillStyle='#ff6b6b';ctx.beginPath();ctx.arc(ht.x,ht.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function connectorPoints(o){let r=o.rot*Math.PI/180,dx=Math.cos(r)*o.width/2,dy=Math.sin(r)*o.width/2;return[{x:o.x-dx,y:o.y-dy},{x:o.x+dx,y:o.y+dy}]}
function connectionExists(a,b){return route.some(n=>n.kind==='connection'&&((n.fromObstacleId===a.id&&n.toObstacleId===b.id)||(n.fromObstacleId===b.id&&n.toObstacleId===a.id)))}
function obstacleNode(o){return route.find(n=>n.kind==='obstacle'&&n.objectId===o.id)}
function drawConnectors(){if(!connectMode||!selected)return;objects.forEach(o=>{if(o===selected)return;let q=project(o.x,o.y,.38),valid=!connectionExists(selected,o),hover=connectionDraft&&hit(q.x,q.y)===o;ctx.save();ctx.strokeStyle=hover?'#fff':valid?'#57e389':'#ff6b6b';ctx.lineWidth=hover?4:2;ctx.setLineDash(hover?[2,2]:[6,4]);ctx.beginPath();ctx.arc(q.x,q.y,22,0,Math.PI*2);ctx.stroke();ctx.restore()});let pts=connectorPoints(selected);pts.forEach((p,i)=>{let q=project(p.x,p.y,.35);ctx.fillStyle=i?'#57e389':'#39bdf8';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#07111f';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i?'S':'E',q.x,q.y)});if(connectionDraft){let a=project(connectionDraft.start.x,connectionDraft.start.y,.35),b=pointerPos(connectionDraft.event);ctx.strokeStyle=hit(b.x,b.y)&&hit(b.x,b.y)!==selected&&!connectionExists(selected,hit(b.x,b.y))?'#57e389':'#ff6b6b';ctx.lineWidth=4;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.setLineDash([])}}
function nodePoints(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return[{x:o?o.x:n.x,y:o?o.y:n.y}]}if(n.kind==='line')return[n.a,n.b];if(n.kind==='curve'||n.kind==='connection')return n.points||[];if(n.kind==='circle'){let a=[];for(let i=0;i<=24;i++){let t=i/24*Math.PI*2;a.push({x:n.cx+Math.cos(t)*n.r,y:n.cy+Math.sin(t)*n.r})}return a}return[{x:n.x,y:n.y}]}
function isCourseNode(n){return n.kind==='obstacle'||n.kind==='point'||n.kind==='connection'}
function allRoutePoints(){return route.filter(isCourseNode).flatMap(n=>n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n))}
function catmull(points,steps=14){if(points.length<2)return points;let out=[];for(let i=0;i<points.length-1;i++){let p0=points[Math.max(0,i-1)],p1=points[i],p2=points[i+1],p3=points[Math.min(points.length-1,i+2)];for(let j=0;j<steps;j++){let t=j/steps,t2=t*t,t3=t2*t;out.push({x:.5*((2*p1.x)+(-p0.x+p2.x)*t+(2*p0.x-5*p1.x+4*p2.x-p3.x)*t2+(-p0.x+3*p1.x-3*p2.x+p3.x)*t3),y:.5*((2*p1.y)+(-p0.y+p2.y)*t+(2*p0.y-5*p1.y+4*p2.y-p3.y)*t2+(-p0.y+3*p1.y-3*p2.y+p3.y)*t3)})}}out.push(points.at(-1));return out}
function arrow(a,b,color='#ffd166'){let p=project(b.x,b.y,.12),q=project(a.x,a.y,.12),ang=Math.atan2(p.y-q.y,p.x-q.x);ctx.save();ctx.translate(p.x,p.y);ctx.rotate(ang);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(12,0);ctx.lineTo(-8,-7);ctx.lineTo(-5,0);ctx.lineTo(-8,7);ctx.closePath();ctx.fill();ctx.restore()}
function drawRouteGeometry(){route.forEach(n=>{if(n.kind==='line'||n.kind==='curve'||n.kind==='connection'){let base=nodePoints(n),shape=n.kind==='line'?base:catmull(base,18),pts=shape.map(p=>project(p.x,p.y,.1));ctx.strokeStyle=n.kind==='connection'?'#57e389':(n.arrow?'#ffd166':'#8de1ff');ctx.lineWidth=n.kind==='connection'?5:4;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();if(n.arrow||n.kind==='connection'){let end=shape.at(-1),prev=shape[Math.max(0,shape.length-2)];arrow(prev,end,n.kind==='connection'?'#57e389':'#ffd166')}}if(n.kind==='circle'){let pts=nodePoints(n).map(p=>project(p.x,p.y,.1));ctx.strokeStyle='#ffd166';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}})}
function drawRouteHandles(){if(!routeSelection)return;let pts=nodePoints(routeSelection);ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#ffd16688';ctx.lineWidth=2;if(routeSelection.kind==='circle'){let c=project(routeSelection.cx,routeSelection.cy,.2),r=project(routeSelection.cx+routeSelection.r,routeSelection.cy,.2);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(r.x,r.y);ctx.stroke()}else if(pts.length>1){ctx.beginPath();pts.forEach((p,i)=>{let q=project(p.x,p.y,.2);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}ctx.setLineDash([]);pts.forEach(p=>{let q=project(p.x,p.y,.22);ctx.fillStyle='#ffd166';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,7,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore()}
function drawMarkers(){route.forEach(n=>{if(n.kind!=='point')return;let p=project(n.x,n.y,.15);ctx.fillStyle=n.marker==='start'?'#57e389':'#ff6b6b';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#07111f';ctx.font='bold 10px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(n.marker==='start'?'S':'L',p.x,p.y)})}
function drawRoute(){let raw=allRoutePoints(),pts=catmull(raw).map(p=>project(p.x,p.y,.16));if(pts.length>1){ctx.strokeStyle='#e8f5ff99';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();let n=Math.max(2,Math.floor(pts.length*(anim?progress:1)));ctx.strokeStyle='#ef476f';ctx.shadowColor='#ef476f';ctx.shadowBlur=12;ctx.lineWidth=8;ctx.beginPath();pts.slice(0,n).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.shadowBlur=0;if(n>2){let k=Math.min(raw.length-1,Math.max(1,Math.floor(n/14)));arrow(raw[k-1],raw[k],'#ffd166')}}}
function draw(){let r=canvas.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);let g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,'#8fc5df');g.addColorStop(.45,'#d7e7e8');g.addColorStop(.46,'#365d3e');g.addColorStop(1,'#17311f');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);groundPoly();drawRouteGeometry();drawRoute();drawMarkers();drawRouteHandles();[...objects].sort((a,b)=>(project(a.x,a.y).depth||0)-(project(b.x,b.y).depth||0)).forEach(drawJump);drawObstacleHandles();drawConnectors();if(draft){let p=project(draft.points?draft.points.at(-1).x:draft.start.x,draft.points?draft.points.at(-1).y:draft.start.y,.2);ctx.strokeStyle='#ffd166';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.stroke()}}
function unproject(sx,sy){let r=canvas.getBoundingClientRect();if(view==='top'){let s=Math.min(r.width/(W+12),r.height/(H+12))*zoom/10;return{x:(sx-r.width/2)/s+W/2,y:(sy-r.height/2)/s+H/2}}let o=project(0,0),px=project(1,0),py=project(0,1),ax=px.x-o.x,ay=px.y-o.y,bx=py.x-o.x,by=py.y-o.y,dx=sx-o.x,dy=sy-o.y,det=ax*by-ay*bx;return{x:(dx*by-dy*bx)/det,y:(ax*dy-ay*dx)/det}}
function hit(sx,sy){let best=null,bd=28;objects.forEach(o=>{let p=project(o.x,o.y),d=Math.hypot(p.x-sx,p.y-sy);if(d<bd){best=o;bd=d}});return best}function hitObstacleHandle(sx,sy){if(!selected)return null;let o=selected,rad=o.rot*Math.PI/180,p=project(o.x,o.y,.25),sz=project(o.x+Math.cos(rad)*o.width/2,o.y+Math.sin(rad)*o.width/2,.25),rot=project(o.x,o.y-4,.25);if(Math.hypot(rot.x-sx,rot.y-sy)<18)return'rotate';if(Math.hypot(sz.x-sx,sz.y-sy)<18)return'size';return null}function hitRouteHandle(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i];if(n.kind==='circle'){let q=project(n.cx+n.r,n.cy,.2);if(Math.hypot(q.x-sx,q.y-sy)<16)return{node:n,index:'radius'}}let pts=nodePoints(n);for(let j=0;j<pts.length;j++){let q=project(pts[j].x,pts[j].y,.2);if(Math.hypot(q.x-sx,q.y-sy)<16)return{node:n,index:j}}}return null}function segmentDistance(p,a,b){let dx=b.x-a.x,dy=b.y-a.y,t=((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy))}function hitRouteGeometry(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i],pts=n.kind==='curve'||n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n);if(n.kind==='circle'){let q=project(n.cx,n.cy,.1),r=project(n.cx+n.r,n.cy,.1).x-q.x;if(Math.abs(Math.hypot(sx-q.x,sy-q.y)-Math.abs(r))<14)return n;continue}for(let j=1;j<pts.length;j++){let a=project(pts[j-1].x,pts[j-1].y,.1),b=project(pts[j].x,pts[j].y,.1);if(segmentDistance({x:sx,y:sy},a,b)<12)return n}}return null}function pointerPos(e){let r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function snapshot(){return JSON.stringify({W,H,objects,assets,sceneRefs,sceneObjects,route})}function restore(s){let d=JSON.parse(s);W=d.W;H=d.H;objects=d.objects||[];assets=d.assets||[];sceneRefs=d.sceneRefs||[];sceneObjects=d.sceneObjects||[];route=d.route||[];routeSelection=null;routeDrag=null;$('#arenaW').value=W;$('#arenaH').value=H;selected=selected&&objects.find(o=>o.id===selected.id)||null;updateUI();draw()}
function history(){past.push(snapshot());if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}function buttons(){$('#undo').disabled=!past.length;$('#redo').disabled=!future.length}function undo(){if(!past.length)return;future.push(snapshot());restore(past.pop())}function redo(){if(!future.length)return;past.push(snapshot());restore(future.pop())}
function addObject(type,x=W/2,y=H/2){history();let o={id:uid(),type,x,y,rot:0,height:type==='Muro'?1.5:1.4,width:type==='Oxer'?2:1.8,num:String(objects.length+1)};objects.push(o);selected=o;updateUI();draw()}function addMarker(marker,x,y){history();route.push({id:uid(),kind:'point',marker,x:Math.max(0,Math.min(W,x)),y:Math.max(0,Math.min(H,y))});placeType=null;setMode('seleccionar');updateUI();draw()}
function setMode(s){$('#modePill').textContent='Modo: '+s}function updateInspector(){let on=!!selected;$('#inspector').style.display=on?'block':'none';$('#emptyInspector').style.display=on?'none':'block';if(!on)return;$('#iType').value=selected.type;$('#iNum').value=selected.num;$('#iRot').value=selected.rot;$('#iHeight').value=selected.height;$('#iWidth').value=selected.width}
function routeLabel(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return o?o.num+' · '+o.type:'Punto fijado'}if(n.kind==='point')return n.marker==='start'?'Salida':'Llegada';if(n.kind==='circle')return'Círculo';if(n.kind==='connection')return'Tramo conectado';if(n.kind==='curve')return'Curva editable';return n.arrow?'Línea con flecha':'Línea recta'}function updateUI(){W=+$ ('#arenaW').value||80;H=+$('#arenaH').value||60;$('#countPill').textContent=objects.length+' obstáculos';updateInspector();let box=$('#routeList');box.innerHTML='';route.forEach((n,i)=>{let d=document.createElement('div');d.className='item';d.dataset.routeIndex=i;d.innerHTML=`<span class="badge">${i+1}</span><span>${routeLabel(n)}</span>`;d.onclick=()=>{routeSelection=n;selected=null;updateUI();draw()};if(n===routeSelection)d.classList.add('active');box.appendChild(d)});$('#addRoutePoint').disabled=!routeSelection||!['line','curve','connection'].includes(routeSelection.kind);let ri=routeSelection?route.indexOf(routeSelection):-1;$('#moveRouteUp').disabled=ri<=0;$('#moveRouteDown').disabled=ri<0||ri>=route.length-1;buttons()}
document.querySelectorAll('.jump[data-type]').forEach(b=>b.onclick=()=>{placeType=b.dataset.type;routeMode=false;$('#routeMode').classList.remove('active');setMode('colocar '+placeType);$('#leftPanel').classList.remove('show')});document.querySelectorAll('.routeTool').forEach(b=>b.onclick=()=>{placeType=b.dataset.tool;routeMode=false;draft=null;$('#routeMode').classList.remove('active');setMode('colocar '+b.dataset.tool);$('#leftPanel').classList.remove('show')});
function renderAssets(){let box=$('#assetList');if(!box)return;box.innerHTML='';assets.forEach(a=>{let size=a.dimensions&&[a.dimensions.width,a.dimensions.height,a.dimensions.depth].some(Boolean)?` · ${a.dimensions.width||'—'}×${a.dimensions.height||'—'}×${a.dimensions.depth||'—'} m`:'';let material=a.material?' · '+a.material:'';let d=document.createElement('div');d.className='item asset-item';d.title='Toca para aplicar al obstáculo seleccionado';d.innerHTML=`<img src="${a.src}" alt="" class="asset-thumb"><span><b>${a.name}</b><br><small>${a.category}${size}${material}${a.description?' · '+a.description:''}</small></span>`;d.onclick=()=>{if(!selected){status('Selecciona un obstáculo para aplicar la referencia');return}history();selected.decals=selected.decals||[];let id=uid();selected.decals.push({id,kind:'logo',name:a.name,src:a.src,target:'side',scale:1,offsetX:0,offsetY:0,rotation:0,assetId:a.id});logoImages[id]=null;updateUI();draw();status('Referencia aplicada al obstáculo')};box.appendChild(d)})}
$('#routeMode').onclick=()=>{routeMode=!routeMode;placeType=null;draft=null;$('#routeMode').classList.toggle('active',routeMode);setMode(routeMode?'definir recorrido':'seleccionar')};$('#clearRoute').onclick=()=>{if(route.length){history();route=[];routeSelection=null;updateUI();draw()}};$('#addRoutePoint').onclick=()=>{if(!routeSelection||!['line','curve'].includes(routeSelection.kind))return;let pts=routeSelection.kind==='line'?[routeSelection.a,routeSelection.b]:routeSelection.points;if(pts.length<2)return;let best=1,dist=-1;for(let i=1;i<pts.length;i++){let d=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);if(d>dist){dist=d;best=i}}let a=pts[best-1],b=pts[best],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};history();if(routeSelection.kind==='line'){routeSelection={...routeSelection,kind:'curve',points:[a,mid,b]};route[route.indexOf(route.find(n=>n.id===routeSelection.id))]=routeSelection}else routeSelection.points.splice(best,0,mid);updateUI();draw()};function moveRoute(delta){let i=routeSelection?route.indexOf(routeSelection):-1,j=i+delta;if(i<0||j<0||j>=route.length)return;history();[route[i],route[j]]=[route[j],route[i]];updateUI();draw()}$('#moveRouteUp').onclick=()=>moveRoute(-1);$('#moveRouteDown').onclick=()=>moveRoute(1);$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#viewTop').onclick=()=>{view='top';$('#camPill').textContent='Cámara: cenital';draw()};$('#view3d').onclick=()=>{view='3d';$('#camPill').textContent='Cámara: 3D';draw()};$('#play').onclick=()=>{if(allRoutePoints().length<2){status('Define al menos 2 elementos en el recorrido');return}anim=!anim;progress=anim?0:1;$('#play').textContent=anim?'⏸ Pausar':'▶ Recorrido'};function status(t){$('#status').textContent='● '+t;setTimeout(()=>$('#status').textContent='● JavaScript ACTIVO',2200)}
function hitConnector(sx,sy){if(!connectMode||!selected)return null;let pts=connectorPoints(selected);for(let i=0;i<pts.length;i++){let q=project(pts[i].x,pts[i].y,.35);if(Math.hypot(q.x-sx,q.y-sy)<20)return{index:i,point:pts[i]}}return null}function hitObstacleHeight(sx,sy){if(!selected)return false;let q=project(selected.x,selected.y,selected.height+.8);return Math.hypot(q.x-sx,q.y-sy)<18}
canvas.addEventListener('pointerdown',e=>{if(!connectMode)return;let q=pointerPos(e),c=hitConnector(q.x,q.y);if(!c)return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);connectionDraft={from:selected,start:c.point,event:e};setMode('arrastra al obstáculo de destino');draw()});canvas.addEventListener('pointermove',e=>{if(!connectionDraft)return;e.stopImmediatePropagation();connectionDraft.event=e;draw()});canvas.addEventListener('pointerup',e=>{if(!connectionDraft)return;e.stopImmediatePropagation();let q=pointerPos(e),target=hit(q.x,q.y),from=connectionDraft.from;if(target&&target!==from){let duplicate=route.some(n=>n.kind==='connection'&&((n.fromObstacleId===from.id&&n.toObstacleId===target.id)||(n.fromObstacleId===target.id&&n.toObstacleId===from.id)));if(!duplicate){let end=connectorPoints(target)[connectionDraft.start.x<from.x?1:0];history();let n={id:uid(),kind:'connection',points:[connectionDraft.start,{x:(connectionDraft.start.x+end.x)/2,y:(connectionDraft.start.y+end.y)/2},end],fromObstacleId:from.id,toObstacleId:target.id};route.push(n);routeSelection=n;selected=target;status('Tramo conectado')}else status('Ese tramo ya existe')}connectionDraft=null;setMode('seleccionar');updateUI();draw()});canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e);if(!hitObstacleHeight(q.x,q.y))return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);obstacleDrag={kind:'height',o:selected,before:snapshot(),startY:e.clientY,startHeight:selected.height};draw()});
canvas.addEventListener('pointermove',e=>{if(!obstacleDrag||obstacleDrag.kind!=='height')return;e.stopImmediatePropagation();let scale=Math.max(8,Math.abs(project(obstacleDrag.o.x,obstacleDrag.o.y,1).y-project(obstacleDrag.o.x,obstacleDrag.o.y,0).y));obstacleDrag.o.height=Math.max(.4,Math.min(4,obstacleDrag.startHeight+(obstacleDrag.startY-e.clientY)/scale));draw()});
canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e),kind=hitObstacleHandle(q.x,q.y);if(!kind)return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);obstacleDrag={kind,o:selected,before:snapshot()};draw()});
canvas.addEventListener('pointermove',e=>{if(!obstacleDrag)return;e.stopImmediatePropagation();let q=pointerPos(e),p=unproject(q.x,q.y),o=obstacleDrag.o;if(obstacleDrag.kind==='rotate')o.rot=Math.round(Math.atan2(p.y-o.y,p.x-o.x)*180/Math.PI);else o.width=Math.max(.8,Math.min(12,Math.hypot(p.x-o.x,p.y-o.y)*2));draw()});
canvas.addEventListener('pointerup',e=>{if(!obstacleDrag)return;e.stopImmediatePropagation();past.push(obstacleDrag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons();obstacleDrag=null;updateInspector();draw()});
canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode)return;let q=pointerPos(e),n=hitRouteGeometry(q.x,q.y);if(!n)return;e.stopImmediatePropagation();routeSelection=n;selected=null;updateUI();draw()});
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);let q=pointerPos(e),h=hit(q.x,q.y),p=unproject(q.x,q.y);if(placeType==='start'||placeType==='finish'){addMarker(placeType,p.x,p.y);return}if(placeType==='curve'){if(!draft){draft={tool:'curve',points:[p]};setMode('añade puntos; doble toque para terminar')}else draft.points.push(p);draw();return}if(placeType==='line'||placeType==='lineArrow'||placeType==='circle'){if(!draft){draft={tool:placeType,start:p};setMode('marca el segundo punto');draw();return}history();let n;if(placeType==='circle')n={id:uid(),kind:'circle',cx:draft.start.x,cy:draft.start.y,r:Math.max(3.5,Math.hypot(p.x-draft.start.x,p.y-draft.start.y))};else n={id:uid(),kind:'line',a:draft.start,b:p,arrow:placeType==='lineArrow'};route.push(n);routeSelection=n;draft=null;placeType=null;setMode('seleccionar');updateUI();draw();return}if(placeType){addObject(placeType,p.x,p.y);placeType=null;setMode('seleccionar');return}let rh=hitRouteHandle(q.x,q.y);if(rh){routeSelection=rh.node;routeDrag={node:rh.node,index:rh.index,before:snapshot()};draw();return}if(routeMode&&h){if(!route.some(n=>n.kind==='obstacle'&&n.objectId===h.id)){history();route.push({id:uid(),kind:'obstacle',objectId:h.id,x:h.x,y:h.y});updateUI();draw()}return}if(h){selected=h;routeSelection=null;drag={o:h,before:snapshot(),moved:false};updateUI();draw()}else if(view==='3d')orbitDrag={x:e.clientX,y:e.clientY,yaw,pitch}});
canvas.addEventListener('pointermove',e=>{let q=pointerPos(e),p=unproject(q.x,q.y);if(routeDrag){let n=routeDrag.node;if(routeDrag.index==='radius')n.r=Math.max(1,Math.min(40,Math.hypot(p.x-n.cx,p.y-n.cy)));else if(n.kind==='circle'){n.cx=p.x;n.cy=p.y}else if(n.kind==='curve')n.points[routeDrag.index]={x:p.x,y:p.y};else if(n.kind==='line'){let k=routeDrag.index?'b':'a';n[k]={x:p.x,y:p.y}}draw()}else if(drag){drag.o.x=Math.max(0,Math.min(W,p.x));drag.o.y=Math.max(0,Math.min(H,p.y));drag.moved=true;draw()}else if(orbitDrag){yaw=orbitDrag.yaw+(e.clientX-orbitDrag.x)*.008;pitch=Math.max(.2,Math.min(1.35,orbitDrag.pitch+(e.clientY-orbitDrag.y)*.006));$('#yaw').value=yaw*180/Math.PI;$('#pitch').value=pitch*180/Math.PI;draw()}});canvas.addEventListener('pointerup',()=>{if(routeDrag){past.push(routeDrag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}if(drag?.moved){past.push(drag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons()}routeDrag=null;drag=null;orbitDrag=null;updateInspector()});canvas.addEventListener('dblclick',()=>{if(placeType==='curve'&&draft?.points?.length>=2){history();let n={id:uid(),kind:'curve',points:draft.points.slice()};route.push(n);routeSelection=n;draft=null;placeType=null;setMode('seleccionar');updateUI();draw()}});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(5,Math.min(18,zoom-e.deltaY*.01));$('#zoom').value=zoom;draw()},{passive:false});
[['arenaW','W'],['arenaH','H']].forEach(([id,k])=>$('#'+id).onchange=()=>{history();updateUI();draw()});[['iType','type'],['iNum','num'],['iRot','rot'],['iHeight','height'],['iWidth','width']].forEach(([id,k])=>$('#'+id).onchange=e=>{if(selected){history();selected[k]=(k==='type'||k==='num')?e.target.value:+e.target.value;updateUI();draw()}});
$('#delete').onclick=()=>{if(!selected)return;history();route=route.map(n=>n.kind==='obstacle'&&n.objectId===selected.id?{...n,kind:'point',objectId:null,x:selected.x,y:selected.y}:n);objects=objects.filter(o=>o!==selected);selected=null;updateUI();draw()};$('#duplicate').onclick=()=>{if(!selected)return;history();let o={...selected,id:uid(),x:selected.x+3,y:selected.y+3,num:String(objects.length+1)};objects.push(o);selected=o;updateUI();draw()};
$('#pitch').oninput=e=>{pitch=+e.target.value*Math.PI/180;draw()};$('#yaw').oninput=e=>{yaw=+e.target.value*Math.PI/180;draw()};$('#zoom').oninput=e=>{zoom=+e.target.value;draw()};$('#grid').onchange=e=>{showGrid=e.target.checked;draw()};$('#shadows').onchange=e=>{showShadows=e.target.checked;draw()};
$('#saveBtn').onclick=()=>{let data={version:'0.5',arena:{width:W,length:H},objects,assets,route};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='faas_equestrian_course.json';a.click();URL.revokeObjectURL(a.href);status('Proyecto guardado')};$('#exportPng').onclick=()=>{draw();canvas.toBlob(blob=>{if(!blob){status('No se pudo exportar la imagen');return}let a=document.createElement('a'),stamp=new Date().toISOString().slice(0,10);a.href=URL.createObjectURL(blob);a.download=`faas_equestrian_course_${stamp}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status('Diseño PNG exportado')},'image/png')};$('#loadBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());objects=data.objects||[];assets=data.assets||[];route=(data.route||[]).map(n=>typeof n==='string'?{id:uid(),kind:'obstacle',objectId:n,x:objects.find(o=>o.id===n)?.x||0,y:objects.find(o=>o.id===n)?.y||0}:n);W=data.arena?.width||80;H=data.arena?.length||60;$('#arenaW').value=W;$('#arenaH').value=H;selected=null;updateUI();draw();status('Proyecto abierto')}catch{status('No se pudo abrir el JSON')}};
$('#demoBtn').onclick=()=>{history();objects=[];route=[];let demo=[['Vertical',12,16,20],['Oxer',27,10,-15],['Vertical',43,18,40],['Doble',61,12,85],['Muro',67,34,10],['Oxer',48,47,-30],['Liverpool',27,42,70],['Triple',12,49,5]];demo.forEach((d,i)=>{let o={id:uid(),type:d[0],x:d[1],y:d[2],rot:d[3],height:d[0]==='Muro'?1.5:1.4,width:d[0]==='Oxer'?2:1.8,num:String(i+1)};objects.push(o);route.push({id:uid(),kind:'obstacle',objectId:o.id,x:o.x,y:o.y})});selected=null;updateUI();draw();status('Demo cargada')};$('#leftToggle').onclick=()=>$('#leftPanel').classList.toggle('show');$('#rightToggle').onclick=()=>$('#rightPanel').classList.toggle('show');
$('#connectMode').onclick=()=>{connectMode=!connectMode;routeMode=false;placeType=null;draft=null;connectionDraft=null;$('#connectMode').classList.toggle('active',connectMode);$('#routeMode').classList.remove('active');setMode(connectMode?'selecciona un obstáculo y arrastra desde E/S':'seleccionar');draw()};$('#routeMode').addEventListener('click',()=>{connectMode=false;connectionDraft=null;$('#connectMode').classList.remove('active')});document.querySelectorAll('.routeTool').forEach(b=>b.addEventListener('click',()=>{connectMode=false;connectionDraft=null;$('#connectMode').classList.remove('active')}));
function tick(t){let dt=(t-last)/1000;last=t;if(anim){progress+=dt/7;if(progress>=1){progress=1;anim=false;$('#play').textContent='▶ Recorrido'}draw()}requestAnimationFrame(tick)}resize();updateUI();$('#status').textContent='● JavaScript ACTIVO';requestAnimationFrame(tick);
function courseDistance(){let pts=allRoutePoints(),m=0;for(let i=1;i<pts.length;i++)m+=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);return m}
function updateMetrics(){let m=courseDistance(),stride=Math.max(2,+$('#strideLength').value||3.5),steps=m?Math.round(m/stride):0;$('#courseMetrics').textContent=`Distancia: ${m.toFixed(1)} m · Trancos estimados: ${steps}`}
function validateCourse(){let nodes=route.filter(n=>n.kind==='obstacle'),start=route.some(n=>n.kind==='point'&&n.marker==='start'),finish=route.some(n=>n.kind==='point'&&n.marker==='finish'),missing=objects.filter(o=>!obstacleNode(o));let messages=[];if(!start)messages.push('falta Salida');if(!finish)messages.push('falta Llegada');if(!nodes.length)messages.push('no hay obstáculos en el recorrido');if(missing.length)messages.push(missing.length+' obstáculo(s) sin ordenar');let ok=!messages.length;updateMetrics();$('#validation').textContent=ok?'✓ Recorrido básico completo: salida, llegada y obstáculos incorporados.':'⚠ '+messages.join(' · ');$('#validation').style.color=ok?'#57e389':'#ffd166';status(ok?'Recorrido válido':'Revisa el recorrido')}
function autoOrder(){let nodes=route.filter(n=>n.kind==='obstacle'),links=route.filter(n=>n.kind==='connection');if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),nearest=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],current=start?nearest(start):nodes[0],ordered=[],used=new Set;while(current&&!used.has(current.objectId)){ordered.push(current);used.add(current.objectId);let link=links.find(n=>n.fromObstacleId===current.objectId&&!used.has(n.toObstacleId));current=link?nodes.find(n=>n.objectId===link.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],link=next&&links.find(l=>l.fromObstacleId===n.objectId&&l.toObstacleId===next.objectId);if(link)course.push(link)});if(start)course.unshift(start);if(finish)course.push(finish);let graphics=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...graphics];routeSelection=null;ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o)o.num=String(i+1)});updateUI();draw();status('Recorrido ordenado')}
$('#autoOrder').onclick=autoOrder;$('#validateCourse').onclick=validateCourse;$('#strideLength').oninput=updateMetrics;
function courseObstacleNodes(){let ns=route.filter(n=>n.kind==='obstacle');route.filter(n=>n.kind==='connection').forEach(c=>[c.fromObstacleId,c.toObstacleId].forEach(id=>{let o=objects.find(x=>x.id===id);if(o&&!ns.some(n=>n.objectId===id))ns.push({id:uid(),kind:'obstacle',objectId:id,x:o.x,y:o.y})}));return ns}
function autoOrder(){let nodes=courseObstacleNodes(),links=route.filter(n=>n.kind==='connection');if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),near=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],cur=start?near(start):nodes[0],ordered=[],used=new Set;while(cur&&!used.has(cur.objectId)){ordered.push(cur);used.add(cur.objectId);let l=links.find(n=>n.fromObstacleId===cur.objectId&&!used.has(n.toObstacleId));cur=l?nodes.find(n=>n.objectId===l.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],l=next&&links.find(x=>x.fromObstacleId===n.objectId&&x.toObstacleId===next.objectId);if(l)course.push(l)});if(start)course.unshift(start);if(finish)course.push(finish);let graphics=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...graphics];ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o)o.num=String(i+1)});routeSelection=null;updateUI();draw();status('Recorrido ordenado')}
function deleteSelectedObstacle(){if(!selected)return;history();let o=selected;route=route.map(n=>n.kind==='obstacle'&&n.objectId===o.id?{...n,kind:'obstacle',objectId:null,x:o.x,y:o.y}:n);route.forEach(n=>{if(n.kind==='connection'&&(n.fromObstacleId===o.id||n.toObstacleId===o.id))n.detached=true});objects=objects.filter(x=>x!==o);selected=null;routeSelection=null;updateUI();draw()}
$('#delete').onclick=deleteSelectedObstacle;
function syncConnections(){route.filter(n=>n.kind==='connection'&&n.points?.length>=2).forEach(n=>{let from=objects.find(o=>o.id===n.fromObstacleId),to=objects.find(o=>o.id===n.toObstacleId);if(from){let ps=connectorPoints(from),p=n.points[0],q=ps.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];n.points[0]={...q}}if(to){let ps=connectorPoints(to),p=n.points.at(-1),q=ps.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];n.points[n.points.length-1]={...q}}})}
function nodePoints(n){if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return[{x:o?o.x:n.x,y:o?o.y:n.y}]}if(n.kind==='line')return[n.a,n.b];if(n.kind==='curve'||n.kind==='connection'){if(n.kind==='connection')syncConnections();return n.points||[]}if(n.kind==='circle'){let a=[];for(let i=0;i<=24;i++){let t=i/24*Math.PI*2;a.push({x:n.cx+Math.cos(t)*n.r,y:n.cy+Math.sin(t)*n.r})}return a}return[{x:n.x,y:n.y}]}
canvas.addEventListener('pointerdown',e=>{let q=pointerPos(e),n=hitRouteGeometry(q.x,q.y);if(!n||!['line','curve','connection'].includes(n.kind))return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);routeSelection=n;selected=null;routeDrag={node:n,index:'move',before:snapshot(),start:unproject(q.x,q.y),original:nodePoints(n).map(p=>({...p}))};updateUI();draw()},true);
canvas.addEventListener('pointermove',e=>{if(!routeDrag||routeDrag.index!=='move')return;e.stopImmediatePropagation();let q=pointerPos(e),p=unproject(q.x,q.y),dx=p.x-routeDrag.start.x,dy=p.y-routeDrag.start.y,n=routeDrag.node;if(n.kind==='line'){n.a={x:routeDrag.original[0].x+dx,y:routeDrag.original[0].y+dy};n.b={x:routeDrag.original[1].x+dx,y:routeDrag.original[1].y+dy}}else n.points=routeDrag.original.map(v=>({x:v.x+dx,y:v.y+dy}));draw()},true);
// Parkour-style interaction layer: separated obstacle controls and green route nodes.
function drawObstacleHandles(){if(!selected)return;let o=selected,p=project(o.x,o.y,.25),rad=o.rot*Math.PI/180,gap=4,sz=project(o.x+Math.cos(rad)*(o.width/2+gap),o.y+Math.sin(rad)*(o.width/2+gap),.25),rot=project(o.x,o.y-(6+gap),.25),ht=project(o.x,o.y,o.height+1.35);ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle='#ffd166aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(sz.x,sz.y);ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.moveTo(p.x,p.y);ctx.lineTo(ht.x,ht.y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#39bdf8';ctx.strokeStyle='#07111f';ctx.beginPath();ctx.arc(rot.x,rot.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd166';ctx.fillRect(sz.x-7,sz.y-7,14,14);ctx.strokeRect(sz.x-7,sz.y-7,14,14);ctx.fillStyle='#ff6b6b';ctx.beginPath();ctx.arc(ht.x,ht.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()}
function hitObstacleHandle(sx,sy){if(!selected)return null;let o=selected,rad=o.rot*Math.PI/180,gap=4,sz=project(o.x+Math.cos(rad)*(o.width/2+gap),o.y+Math.sin(rad)*(o.width/2+gap),.25),rot=project(o.x,o.y-(6+gap),.25);if(Math.hypot(rot.x-sx,rot.y-sy)<18)return'rotate';if(Math.hypot(sz.x-sx,sz.y-sy)<18)return'size';return null}
function drawRouteHandles(){if(!routeSelection)return;let pts=nodePoints(routeSelection);ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#57e38988';ctx.lineWidth=2;if(routeSelection.kind==='circle'){let c=project(routeSelection.cx,routeSelection.cy,.2),r=project(routeSelection.cx+routeSelection.r,routeSelection.cy,.2);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(r.x,r.y);ctx.stroke()}else if(pts.length>1){ctx.beginPath();pts.forEach((p,i)=>{let q=project(p.x,p.y,.2);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}ctx.setLineDash([]);pts.forEach(p=>{let q=project(p.x,p.y,.22);ctx.fillStyle='#57e389';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore()}
function hitObstacleHeight(sx,sy){if(!selected)return false;let q=project(selected.x,selected.y,selected.height+1.35);return Math.hypot(q.x-sx,q.y-sy)<18}
function hitRouteGeometry(sx,sy){if(hitRouteHandle(sx,sy))return null;for(let i=route.length-1;i>=0;i--){let n=route[i],pts=n.kind==='curve'||n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n);if(n.kind==='circle'){let q=project(n.cx,n.cy,.1),r=project(n.cx+n.r,n.cy,.1).x-q.x;if(Math.abs(Math.hypot(sx-q.x,sy-q.y)-Math.abs(r))<14)return n;continue}for(let j=1;j<pts.length;j++){let a=project(pts[j-1].x,pts[j-1].y,.1),b=project(pts[j].x,pts[j].y,.1);if(segmentDistance({x:sx,y:sy},a,b)<12)return n}}return null}
function lineNode(){return routeSelection&&['line','curve','connection','circle'].includes(routeSelection.kind)?routeSelection:null}
function refreshLineInspector(){let n=lineNode(),box=$('#lineInspector');if(!box)return;box.style.display=n?'block':'none';if(n){$('#lineTitle').textContent=routeLabel(n);$('#deleteLinePoint').disabled=!['curve','connection'].includes(n.kind)||nodePoints(n).length<=3;$('#addLinePoint').disabled=n.kind==='circle'} }
function updateInspector(){let on=!!selected;$('#inspector').style.display=on?'block':'none';$('#emptyInspector').style.display=on?'none':'block';if(on){$('#iType').value=selected.type;$('#iNum').value=selected.num;$('#iRot').value=selected.rot;$('#iHeight').value=selected.height;$('#iWidth').value=selected.width}refreshLineInspector()}
function routeEditPoints(n){if(n.kind==='circle')return[{x:n.cx,y:n.cy},{x:n.cx+n.r,y:n.cy}];return nodePoints(n)}
function drawRouteHandles(){if(!routeSelection)return;let n=routeSelection,pts=routeEditPoints(n);ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='#57e38988';ctx.lineWidth=2;if(n.kind==='circle'){let c=project(n.cx,n.cy,.2),r=project(n.cx+n.r,n.cy,.2);ctx.beginPath();ctx.moveTo(c.x,c.y);ctx.lineTo(r.x,r.y);ctx.stroke()}else if(pts.length>1){ctx.beginPath();pts.forEach((p,i)=>{let q=project(p.x,p.y,.2);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}ctx.setLineDash([]);pts.forEach(p=>{let q=project(p.x,p.y,.22);ctx.fillStyle='#57e389';ctx.strokeStyle='#07111f';ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,8,0,Math.PI*2);ctx.fill();ctx.stroke()});ctx.restore()}
function hitRouteHandle(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i];if(!['line','curve','connection','circle','courseControl'].includes(n.kind))continue;let pts=routeEditPoints(n);for(let j=0;j<pts.length;j++){let q=project(pts[j].x,pts[j].y,.2);if(Math.hypot(q.x-sx,q.y-sy)<18)return{node:n,index:n.kind==='circle'?(j?'radius':'center'):j}}}return null}
function cloneLine(n){let c=JSON.parse(JSON.stringify(n)),dx=3,dy=3;c.id=uid();if(c.kind==='line'){c.a.x+=dx;c.a.y+=dy;c.b.x+=dx;c.b.y+=dy}else if(c.kind==='circle'){c.cx+=dx;c.cy+=dy}else{c.points=(c.points||[]).map(p=>({x:p.x+dx,y:p.y+dy}))}return c}
$('#duplicateLine').onclick=()=>{let n=lineNode();if(!n)return;history();let c=cloneLine(n);if(c.kind==='connection'){c.kind='curve';delete c.fromObstacleId;delete c.toObstacleId;delete c.detached}route.push(c);routeSelection=c;selected=null;updateUI();draw();status('Línea duplicada')};
$('#deleteLine').onclick=()=>{let n=lineNode();if(!n)return;history();route=route.filter(x=>x!==n);routeSelection=null;updateUI();draw();status('Línea eliminada')};
$('#addLinePoint').onclick=()=>{let n=lineNode();if(!n||n.kind==='circle')return;let pts=n.kind==='line'?[n.a,n.b]:n.points;if(pts.length<2)return;let best=1,dist=-1;for(let i=1;i<pts.length;i++){let d=Math.hypot(pts[i].x-pts[i-1].x,pts[i].y-pts[i-1].y);if(d>dist){dist=d;best=i}}let a=pts[best-1],b=pts[best],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};history();if(n.kind==='line'){n.kind='curve';n.points=[{...a},mid,{...b}];delete n.a;delete n.b}else n.points.splice(best,0,mid);updateUI();draw();status('Punto añadido')};
$('#deleteLinePoint').onclick=()=>{let n=lineNode();if(!n||!['curve','connection'].includes(n.kind)||n.points.length<=3)return;history();n.points.splice(n.points.length-2,1);updateUI();draw();status('Punto eliminado')};
canvas.addEventListener('pointermove',e=>{if(!routeDrag||routeDrag.index==='move')return;let n=routeDrag.node,q=pointerPos(e),p=unproject(q.x,q.y);if(n.kind==='connection'&&typeof routeDrag.index==='number'){if(routeDrag.index>0&&routeDrag.index<n.points.length-1)n.points[routeDrag.index]={x:p.x,y:p.y};draw()}else if(n.kind==='circle'){if(routeDrag.index==='center'){n.cx=p.x;n.cy=p.y}else if(routeDrag.index==='radius')n.r=Math.max(1,Math.min(40,Math.hypot(p.x-n.cx,p.y-n.cy)));draw()}},{passive:true});
// Advanced route layer: styles, generic joins, ordered execution and course control points.
function isCourseNode(n){return n.kind==='obstacle'||n.kind==='point'||n.kind==='courseControl'||(n.kind==='connection'&&n.course!==false&&n.fromObstacleId&&n.toObstacleId)}
function nodePoints(n){if(n.kind==='courseControl')return[{x:n.x,y:n.y}];if(n.kind==='obstacle'){let o=objects.find(x=>x.id===n.objectId);return[{x:o?o.x:n.x,y:o?o.y:n.y}]}if(n.kind==='line')return[n.a,n.b];if(n.kind==='curve'||n.kind==='connection'){if(n.kind==='connection')syncConnections();return n.points||[]}if(n.kind==='circle'){let a=[];for(let i=0;i<=32;i++){let t=i/32*Math.PI*2;a.push({x:n.cx+Math.cos(t)*n.r,y:n.cy+Math.sin(t)*n.r})}return a}return[{x:n.x,y:n.y}]}
function routeStyle(n){return{color:n.color|| (n.kind==='connection'?'#57e389':n.arrow?'#ffd166':n.kind==='circle'?'#ffd166':'#8de1ff'),width:+n.width|| (n.kind==='connection'?5:n.kind==='circle'?3:4),dash:n.dash==='dashed'?[10,8]:[]}}
function drawStyledPath(shape,n,partial=1){if(shape.length<2)return;let s=routeStyle(n),pts=shape.slice(0,Math.max(2,Math.ceil(shape.length*partial))).map(p=>project(p.x,p.y,.1));ctx.save();ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.setLineDash(s.dash);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();if((n.arrow||n.kind==='connection')&&pts.length>1)arrow(shape[Math.max(0,Math.ceil(shape.length*partial)-2)],shape[Math.max(0,Math.ceil(shape.length*partial)-1)],s.color)}
function drawRouteGeometry(){route.forEach(n=>{if(['line','curve','connection'].includes(n.kind)){let base=nodePoints(n),shape=n.kind==='line'?base:catmull(base,18);drawStyledPath(shape,n)}if(n.kind==='circle')drawStyledPath(nodePoints(n),n)});if(executionRunning)drawExecutionOverlay()}
function drawExecutionOverlay(){let n=executionQueue[executionIndex];if(!n)return;let shape=n.kind==='courseRun'?catmull(allRoutePoints(),18):n.kind==='line'?nodePoints(n):n.kind==='circle'?nodePoints(n):catmull(nodePoints(n),18);drawStyledPath(shape,n,executionProgress)}
function drawRoute(){let raw=allRoutePoints(),pts=catmull(raw).map(p=>project(p.x,p.y,.16));if(pts.length>1){ctx.save();ctx.strokeStyle='#e8f5ff55';ctx.lineWidth=3;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();if(!executionRunning){let n=Math.max(2,Math.floor(pts.length*(anim?progress:1)));ctx.save();ctx.strokeStyle='#ef476f';ctx.shadowColor='#ef476f';ctx.shadowBlur=12;ctx.lineWidth=8;ctx.beginPath();pts.slice(0,n).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore()}}}
function styleInspector(){let n=lineNode();if(!n)return;$('#lineColor').value=n.color||routeStyle(n).color;$('#lineWidth').value=n.width||routeStyle(n).width;$('#lineDash').value=n.dash||'solid'}
function refreshLineInspector(){let n=lineNode(),box=$('#lineInspector');if(!box)return;box.style.display=n?'block':'none';if(n){$('#lineTitle').textContent=routeLabel(n);$('#deleteLinePoint').disabled=!['curve','connection'].includes(n.kind)||nodePoints(n).length<=3;$('#addLinePoint').disabled=n.kind==='circle';$('#smoothLine').disabled=!['line','curve','connection'].includes(n.kind);styleInspector()}}
function applyLineStyle(key,value){let n=lineNode();if(!n)return;history();if(key==='width')n.width=+value;else n[key]=value;updateUI();draw()}
$('#lineColor').onchange=e=>applyLineStyle('color',e.target.value);$('#lineWidth').oninput=e=>{let n=lineNode();if(n){n.width=+e.target.value;draw()}};$('#lineWidth').onchange=e=>applyLineStyle('width',e.target.value);$('#lineDash').onchange=e=>applyLineStyle('dash',e.target.value);
function executionLabel(n){return n.kind==='courseRun'?'RECORRIDO':routeLabel(n)}
function startExecution(){let items=[];if(allRoutePoints().length>1)items.push({kind:'courseRun',id:'course'});route.filter(n=>['line','curve','connection','circle'].includes(n.kind)).forEach(n=>items.push(n));if(!items.length){status('No hay líneas ni recorrido para ejecutar');return}let ordered=items;if(items.length>1){let labels=items.map((n,i)=>String.fromCharCode(65+i)+'='+executionLabel(n)).join(' · '),answer=prompt('¿En qué orden desea ejecutar?\n'+labels+'\nEscriba las letras separadas por comas, por ejemplo: A,B,C');if(answer===null)return;let wanted=answer.toUpperCase().replace(/\s/g,'').split(',').filter(Boolean),map=new Map(items.map((n,i)=>[String.fromCharCode(65+i),n]));if(wanted.length!==items.length||wanted.some(x=>!map.has(x))){status('Orden no válido: use todas las letras');return}ordered=wanted.map(x=>map.get(x))}executionQueue=ordered;executionIndex=0;executionProgress=0;executionRunning=true;anim=false;$('#play').textContent='⏸ Pausar';status('Ejecución iniciada')}
$('#play').onclick=()=>{if(executionRunning){executionRunning=false;$('#play').textContent='▶ Ejecutar';status('Ejecución pausada')}else startExecution()};
function tick(t){let dt=(t-last)/1000;last=t;if(executionRunning){executionProgress+=dt*executionSpeed/4;if(executionProgress>=1){executionProgress=0;executionIndex++;if(executionIndex>=executionQueue.length){executionRunning=false;executionIndex=0;$('#play').textContent='▶ Ejecutar';status('Ejecución terminada')}}draw()}requestAnimationFrame(tick)}
function geometryEndpoint(n,lastPoint=false){let p=n.kind==='circle'?{x:n.cx+n.r,y:n.cy}:nodePoints(n)[lastPoint?-1:0];return p?{x:p.x,y:p.y}:null}
$('#connectGeometry').onclick=()=>{let n=lineNode();if(!n)return;geometryConnectMode=true;geometryConnectSource=n;setMode('toca otra línea, curva, flecha o círculo');status('Selecciona el segundo elemento')};
canvas.addEventListener('pointerdown',e=>{if(!geometryConnectMode||!geometryConnectSource)return;let q=pointerPos(e),target=hitRouteGeometry(q.x,q.y);if(!target||target===geometryConnectSource)return;e.stopPropagation();let a=geometryEndpoint(geometryConnectSource,true),b=geometryEndpoint(target,false);if(a&&b){history();route.push({id:uid(),kind:'connection',points:[a,{x:(a.x+b.x)/2,y:(a.y+b.y)/2},b],course:false,fromRef:geometryConnectSource.id,toRef:target.id});routeSelection=route.at(-1);geometryConnectMode=false;geometryConnectSource=null;setMode('seleccionar');updateUI();draw();status('Elementos unidos')}},{passive:false});
function nearestRouteTarget(p){let best=null,dist=Infinity;route.filter(n=>['line','curve','connection','circle'].includes(n.kind)).forEach(n=>{let pts=nodePoints(n);for(let i=1;i<pts.length;i++){let d=segmentDistance(p,pts[i-1],pts[i]);if(d<dist){dist=d;best={node:n,point:pts[i]}}}});let raw=allRoutePoints();for(let i=1;i<raw.length;i++){let d=segmentDistance(p,raw[i-1],raw[i]);if(d<dist){dist=d;best={node:{kind:'courseRun'},point:raw[i]}}}return best&&dist<3.5?best:null}
function addObject(type,x=W/2,y=H/2){history();let o={id:uid(),type,x,y,rot:0,height:type==='Muro'?1.5:1.4,width:type==='Oxer'?2:1.8,num:String(objects.length+1)};objects.push(o);selected=o;let target=nearestRouteTarget({x,y});if(target&&confirm('CONECTAR A LA LÍNEA O RECORRIDO')){let p=target.point;route.push({id:uid(),kind:'connection',points:[{x,y},{x:p.x,y:p.y}],course:false,fromObstacleId:o.id,targetRef:target.node.id||'course'});status('Obstáculo conectado')}updateUI();draw()}
$('#addCoursePoint').onclick=()=>{let base=courseBaseNodes(),best=1,dist=-1;if(base.length<2)return;for(let i=1;i<base.length;i++){let a=courseNodeEndpoint(base[i-1],true),b=courseNodeEndpoint(base[i],false),d=Math.hypot(b.x-a.x,b.y-a.y);if(d>dist){dist=d;best=i}}let a=courseNodeEndpoint(base[best-1],true),b=courseNodeEndpoint(base[best],false);history();let n={id:uid(),kind:'courseControl',x:(a.x+b.x)/2,y:(a.y+b.y)/2,afterNodeId:base[best-1].id};route.push(n);routeSelection=n;selected=null;updateUI();draw();status('Punto verde añadido al recorrido')};
canvas.addEventListener('pointermove',e=>{if(!routeDrag||routeDrag.index==='move')return;let n=routeDrag.node,q=pointerPos(e),p=unproject(q.x,q.y);if(n.kind==='courseControl'){n.x=p.x;n.y=p.y;updateMetrics();draw()}},{passive:true});
drawObstacleHandles=function(){if(!selected)return;let o=selected,p=project(o.x,o.y,.25),rad=o.rot*Math.PI/180,gap=4,sz=project(o.x+Math.cos(rad)*(o.width/2+gap),o.y+Math.sin(rad)*(o.width/2+gap),.25),rot=project(o.x,o.y-(6+gap),.25),ht=project(o.x,o.y,o.height+1.35),dir=project(o.x+Math.cos(rad)*Math.max(2,o.width/2),o.y+Math.sin(rad)*Math.max(2,o.width/2),.38);ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle='#ffd166aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(sz.x,sz.y);ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.moveTo(p.x,p.y);ctx.lineTo(ht.x,ht.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#39bdf8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(dir.x,dir.y);ctx.stroke();ctx.fillStyle='#39bdf8';ctx.strokeStyle='#07111f';ctx.beginPath();ctx.arc(rot.x,rot.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd166';ctx.fillRect(sz.x-7,sz.y-7,14,14);ctx.strokeRect(sz.x-7,sz.y-7,14,14);ctx.fillStyle='#ff6b6b';ctx.beginPath();ctx.arc(ht.x,ht.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()};
$('#iNum').onchange=e=>{if(selected){history();selected.num=e.target.value;selected.manualNum=true;updateUI();draw()}};
function autoOrder(){let nodes=courseObstacleNodes(),links=route.filter(n=>n.kind==='connection'&&n.fromObstacleId&&n.toObstacleId);if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),near=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],cur=start?near(start):nodes[0],ordered=[],used=new Set;while(cur&&!used.has(cur.objectId)){ordered.push(cur);used.add(cur.objectId);let l=links.find(n=>n.fromObstacleId===cur.objectId&&!used.has(n.toObstacleId));cur=l?nodes.find(n=>n.objectId===l.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],l=next&&links.find(x=>x.fromObstacleId===n.objectId&&x.toObstacleId===next.objectId);if(l)course.push(l)});if(start)course.unshift(start);if(finish)course.push(finish);let graphics=route.filter(n=>!['obstacle','connection','point','courseControl'].includes(n.kind));history();route=[...course,...graphics];ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o&&!o.manualNum)o.num=String(i+1)});routeSelection=null;updateUI();draw();status('Recorrido ordenado')}
// Correcciones de interacción y ejecución: una sola capa táctil para los controles avanzados.
function obstacleDirectionPoint(o){let r=o.rot*Math.PI/180,gap=4,len=Math.max(2,o.width/2+gap);return{x:o.x+Math.cos(r)*len,y:o.y+Math.sin(r)*len}}
drawObstacleHandles=function(){if(!selected)return;let o=selected,p=project(o.x,o.y,.25),dir=obstacleDirectionPoint(o),rot=project(dir.x,dir.y,.38),sz=project(o.x+Math.cos(o.rot*Math.PI/180)*(o.width/2+4),o.y+Math.sin(o.rot*Math.PI/180)*(o.width/2+4),.25),ht=project(o.x,o.y,o.height+1.35);ctx.save();ctx.setLineDash([5,4]);ctx.strokeStyle='#ffd166aa';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(sz.x,sz.y);ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.moveTo(p.x,p.y);ctx.lineTo(ht.x,ht.y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#39bdf8';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(rot.x,rot.y);ctx.stroke();ctx.fillStyle='#39bdf8';ctx.strokeStyle='#07111f';ctx.beginPath();ctx.arc(rot.x,rot.y,9,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#ffd166';ctx.fillRect(sz.x-7,sz.y-7,14,14);ctx.strokeRect(sz.x-7,sz.y-7,14,14);ctx.fillStyle='#ff6b6b';ctx.beginPath();ctx.arc(ht.x,ht.y,8,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore()};
hitObstacleHandle=function(sx,sy){if(!selected)return null;let o=selected,rot=project(obstacleDirectionPoint(o).x,obstacleDirectionPoint(o).y,.38),sz=project(o.x+Math.cos(o.rot*Math.PI/180)*(o.width/2+4),o.y+Math.sin(o.rot*Math.PI/180)*(o.width/2+4),.25);if(Math.hypot(rot.x-sx,rot.y-sy)<22)return'rotate';if(Math.hypot(sz.x-sx,sz.y-sy)<22)return'size';return null};
hitRouteGeometry=function(sx,sy){for(let i=route.length-1;i>=0;i--){let n=route[i];if(!['line','curve','connection','circle'].includes(n.kind))continue;if(n.kind==='circle'){let c=project(n.cx,n.cy,.1),r=Math.abs(project(n.cx+n.r,n.cy,.1).x-c.x),d=Math.hypot(sx-c.x,sy-c.y);if(d<18||Math.abs(d-r)<16)return n;continue}let pts=n.kind==='curve'||n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n);for(let j=1;j<pts.length;j++){let a=project(pts[j-1].x,pts[j-1].y,.1),b=project(pts[j].x,pts[j].y,.1);if(segmentDistance({x:sx,y:sy},a,b)<16)return n}}return null};
// La conexión entre geometrías se procesa en captura para que no compita con los puntos verdes.
canvas.addEventListener('pointerdown',e=>{if(!geometryConnectMode||!geometryConnectSource)return;let q=pointerPos(e),target=hitRouteGeometry(q.x,q.y);e.stopImmediatePropagation();if(!target||target===geometryConnectSource){status('Toca otra línea, curva, flecha o círculo');return}let a=geometryEndpoint(geometryConnectSource,true),b=geometryEndpoint(target,false);if(!a||!b)return;history();let c={id:uid(),kind:'connection',points:[a,{x:(a.x+b.x)/2,y:(a.y+b.y)/2},b],course:false,fromRef:geometryConnectSource.id,toRef:target.id};route.push(c);routeSelection=c;selected=null;geometryConnectMode=false;geometryConnectSource=null;setMode('seleccionar');updateUI();draw();status('Elementos unidos')},true);
// Al tocar el círculo central se selecciona; el control central lo traslada y el exterior cambia el radio.
function executionStyle(){return{color:executionColor,width:executionWidth,dash:executionDash==='dashed'?[10,8]:executionDash==='dotted'?[2,8]:[]}}
function drawExecutionOverlay(){let n=executionQueue[executionIndex];if(!n)return;let shape=n.kind==='courseRun'?catmull(allRoutePoints(),18):n.kind==='line'?nodePoints(n):n.kind==='circle'?nodePoints(n):catmull(nodePoints(n),18);if(shape.length<2)return;let s=executionStyle(),pts=shape.slice(0,Math.max(2,Math.ceil(shape.length*executionProgress))).map(p=>project(p.x,p.y,.1));ctx.save();ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.setLineDash(s.dash);ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();if(n.arrow&&pts.length>1)arrow(shape[Math.max(0,Math.ceil(shape.length*executionProgress)-2)],shape[Math.max(0,Math.ceil(shape.length*executionProgress)-1)],s.color)}
function buildExecutionQueue(){let q=[],courseAdded=false;route.forEach(n=>{if(isCourseNode(n)){if(!courseAdded){q.push({kind:'courseRun',id:'course'});courseAdded=true}}else if(['line','curve','connection','circle'].includes(n.kind))q.push(n)});if(!courseAdded&&allRoutePoints().length>1)q.unshift({kind:'courseRun',id:'course'});return q}
startExecution=function(){executionQueue=buildExecutionQueue();if(!executionQueue.length){status('No hay líneas ni recorrido para ejecutar');return}executionIndex=0;executionProgress=0;executionRunning=true;anim=false;$('#play').textContent='⏸ Pausar';status('Ejecución iniciada')};
$('#executionSpeed').oninput=e=>{executionSpeed=+e.target.value;$('#executionSpeedValue').textContent=executionSpeed+'×'};$('#executionColor').oninput=e=>{executionColor=e.target.value;draw()};$('#executionWidth').oninput=e=>{executionWidth=+e.target.value;draw()};$('#executionDash').onchange=e=>{executionDash=e.target.value;draw()};
function smoothEditablePoints(points,passes=2){let next=points.map(p=>({...p}));for(let pass=0;pass<passes;pass++){next=next.map((p,i)=>i===0||i===next.length-1?{...p}:{x:p.x*.5+(next[i-1].x+next[i+1].x)*.25,y:p.y*.5+(next[i-1].y+next[i+1].y)*.25})}return next}
$('#smoothLine').onclick=()=>{let n=lineNode();if(!n||!['line','curve','connection'].includes(n.kind))return;history();if(n.kind==='line'){let a={...n.a},b={...n.b};n.kind='curve';n.points=[a,{x:(a.x+b.x)/2,y:(a.y+b.y)/2},b];delete n.a;delete n.b}if(n.points?.length>=3)n.points=smoothEditablePoints(n.points);updateUI();draw();status('Trazado mejorado')};
// Modelo canónico del recorrido: los puntos verdes quedan asociados al tramo que modifican.
function courseBaseNodes(){return route.filter(n=>n.kind==='obstacle'||n.kind==='point'||(n.kind==='connection'&&n.course!==false&&n.fromObstacleId&&n.toObstacleId))}
function courseNodeEndpoint(n,lastPoint){let pts=nodePoints(n);return pts[lastPoint?pts.length-1:0]||{x:0,y:0}}
function allRoutePoints(){let base=courseBaseNodes(),controls=route.filter(n=>n.kind==='courseControl'),out=[];base.forEach(n=>{let pts=n.kind==='connection'?catmull(nodePoints(n),18):nodePoints(n);pts.forEach((p,i)=>{if(!out.length||i||Math.hypot(out.at(-1).x-p.x,out.at(-1).y-p.y)>0.001)out.push({...p})});controls.filter(c=>c.afterNodeId===n.id).forEach(c=>out.push({x:c.x,y:c.y}))});controls.filter(c=>!c.afterNodeId||!base.some(n=>n.id===c.afterNodeId)).forEach(c=>out.push({x:c.x,y:c.y}));return out}
function autoOrder(){let nodes=courseObstacleNodes(),links=route.filter(n=>n.kind==='connection'&&n.fromObstacleId&&n.toObstacleId);if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),near=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],cur=start?near(start):nodes[0],ordered=[],used=new Set;while(cur&&!used.has(cur.objectId)){ordered.push(cur);used.add(cur.objectId);let l=links.find(n=>n.fromObstacleId===cur.objectId&&!used.has(n.toObstacleId));cur=l?nodes.find(n=>n.objectId===l.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],l=next&&links.find(x=>x.fromObstacleId===n.objectId&&x.toObstacleId===next.objectId);if(l)course.push(l)});if(start)course.unshift(start);if(finish)course.push(finish);let extras=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...extras];ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o&&!o.manualNum)o.num=String(i+1)});routeSelection=null;updateUI();draw();status('Recorrido ordenado')}
$('#autoOrder').onclick=autoOrder;
const updateUIWithAssets=updateUI;updateUI=function(){updateUIWithAssets();renderAssets()};
$('#addAsset').onclick=()=>$('#assetFileInput').click();
$('#assetFileInput').onchange=e=>{let file=e.target.files?.[0];if(!file)return;let reader=new FileReader();reader.onload=()=>{let name=prompt('Nombre del elemento',file.name)||file.name;let category=$('#assetCategory').value||'Referencia';let description=$('#assetDescription').value||'';let dimensions={width:+$('#assetWidth').value||null,height:+$('#assetHeight').value||null,depth:+$('#assetDepth').value||null};let material=$('#assetMaterial').value||'';assets.push({id:uid(),name,category,description,dimensions,material,mime:file.type,src:reader.result,createdAt:new Date().toISOString(),futureAssetType:category.toLowerCase()});['assetDescription','assetWidth','assetHeight','assetDepth','assetMaterial'].forEach(id=>$('#'+id).value='');updateUI();status('Referencia añadida a la biblioteca')};reader.readAsDataURL(file)};
function drawObstacleAddons(o){(o.parts||[]).forEach(part=>{let r=o.rot*Math.PI/180,factor=part.width||1,dx=Math.cos(r)*o.width/2*factor,dy=Math.sin(r)*o.width/2*factor,z=part.z??o.height*.55,a=project(o.x-dx,o.y-dy,z),b=project(o.x+dx,o.y+dy,z);ctx.save();ctx.strokeStyle=part.color||'#f7f3e8';ctx.fillStyle=(part.color||'#f7f3e8')+'bb';ctx.lineWidth=Math.max(3,a.s*.18);if(['bar','support','rail'].includes(part.kind)){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}if(['panel','plank','door','filler','wall','decor'].includes(part.kind)){let ab=project(o.x-dx,o.y-dy,z+(part.height||o.height*.55)),bb=project(o.x+dx,o.y+dy,z+(part.height||o.height*.55));ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(bb.x,bb.y);ctx.lineTo(ab.x,ab.y);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore()})}
function drawObstacleDecals(o){(o.decals||[]).forEach(d=>{if(!logoImages[d.id]&&typeof Image!=='undefined'){let image=new Image();image.onload=draw;image.src=d.src;logoImages[d.id]=image}let image=logoImages[d.id];if(!image||!image.complete)return;let r=o.rot*Math.PI/180,dx=o.width*.32,logoZ=Math.max(.2,o.height*(.42+(d.offsetY||0)*.25)),center=project(o.x+Math.cos(r)*(d.offsetX||0)*o.width,o.y+Math.sin(r)*(d.offsetX||0)*o.width,logoZ),w=Math.max(10,project(o.x+dx*Math.cos(r),o.y+dx*Math.sin(r),logoZ).x-project(o.x-dx*Math.cos(r),o.y-dx*Math.sin(r),logoZ).x)*(d.scale||1),h=Math.max(8,w*.42);ctx.save();ctx.globalAlpha=.95;ctx.translate(center.x,center.y);ctx.rotate((d.rotation||0)*Math.PI/180);ctx.drawImage(image,-w/2,-h/2,w,h);ctx.restore()})}
const baseDrawJump=drawJump;drawJump=function(o){baseDrawJump(o);drawObstacleAddons(o);drawObstacleDecals(o)};
function obstaclePart(kind){if(!selected)return;history();selected.parts=selected.parts||[];let color=$('#partColor').value||'#f7f3e8',material=$('#partMaterial').value||'',height=kind==='wall'?selected.height:kind==='door'?Math.max(.8,selected.height*.7):Math.max(.35,selected.height*.55);selected.parts.push(['bar','support','rail'].includes(kind)?{id:uid(),kind,z:selected.height*.55,width:1,color,material}:{id:uid(),kind,z:kind==='wall'?0:Math.max(0,selected.height*.12),height,width:1,color,material});updateUI();draw();status((({panel:'Panel',plank:'Tablón',door:'Puerta',filler:'Relleno',wall:'Muro',support:'Soporte',rail:'Riel',decor:'Decoración'})[kind]||'Componente')+' añadido')}
$('#addObstacleBar').onclick=()=>obstaclePart('bar');$('#addObstaclePanel').onclick=()=>obstaclePart('panel');
function activeLogo(){return selected?.decals?.at(-1)||null}function updateLogo(key,value){let d=activeLogo();if(!d)return;history();d[key]=+value;draw()}
$('#addObstacleLogo').onclick=()=>{if(!selected){status('Selecciona un obstáculo primero');return}$('#obstacleLogoInput').click()};$('#obstacleLogoInput').onchange=e=>{let file=e.target.files?.[0];if(!selected||!file)return;let reader=new FileReader();reader.onload=()=>{history();selected.decals=selected.decals||[];let id=uid();selected.decals.push({id,kind:'logo',src:reader.result,target:$('#assetApplyTarget').value||'side',scale:1,offsetX:0,offsetY:0,rotation:0});logoImages[id]=null;updateUI();draw();status('Referencia aplicada al obstáculo')};reader.readAsDataURL(file)};$('#logoScale').oninput=e=>updateLogo('scale',e.target.value);$('#logoOffsetX').oninput=e=>updateLogo('offsetX',e.target.value);$('#logoOffsetY').oninput=e=>updateLogo('offsetY',e.target.value);$('#logoRotation').oninput=e=>updateLogo('rotation',e.target.value);
function applyReferenceAsset(a){let target=$('#assetApplyTarget')?.value||'side';if(!selected&&['ambiente','escenario'].includes(a.category.toLowerCase())){history();sceneRefs.push({id:uid(),assetId:a.id,name:a.name,category:a.category,src:a.src});status('Referencia de escenario incorporada');return}if(!selected){status('Selecciona un obstáculo para aplicar la referencia');return}history();selected.decals=selected.decals||[];let id=uid();selected.decals.push({id,kind:'logo',name:a.name,src:a.src,target,scale:1,offsetX:0,offsetY:0,rotation:0,assetId:a.id});logoImages[id]=null;updateUI();draw();status('Referencia aplicada al obstáculo')}
renderAssets=function(){let box=$('#assetList');if(!box)return;box.innerHTML='';assets.forEach(a=>{let d=document.createElement('div');d.className='item asset-item';d.title='Toca para aplicar al obstáculo o escenario';d.innerHTML=`<img src="${a.src}" alt="" class="asset-thumb"><span><b>${a.name}</b><br><small>${a.category}${a.description?' · '+a.description:''}</small></span>`;d.onclick=()=>applyReferenceAsset(a);box.appendChild(d)})};
$('#saveBtn').onclick=()=>{let data={version:'0.6',arena:{width:W,length:H},objects,assets,sceneRefs,route};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='faas_equestrian_course.json';a.click();URL.revokeObjectURL(a.href);status('Proyecto guardado')};
$('#fileInput').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());objects=data.objects||[];assets=data.assets||[];sceneRefs=data.sceneRefs||[];route=(data.route||[]).map(n=>typeof n==='string'?{id:uid(),kind:'obstacle',objectId:n,x:objects.find(o=>o.id===n)?.x||0,y:objects.find(o=>o.id===n)?.y||0}:n);W=data.arena?.width||80;H=data.arena?.length||60;$('#arenaW').value=W;$('#arenaH').value=H;selected=null;updateUI();draw();status('Proyecto abierto')}catch{status('No se pudo abrir el JSON')}};
function renderObstacleComponents(){let box=$('#componentList');if(!box){box=document.createElement('div');box.id='componentList';box.className='list';let inspector=$('#inspector');if(inspector)inspector.insertBefore(box,inspector.firstChild)}if(!box)return;box.innerHTML='';if(!selected){selectedPart=null;return}let parts=[...(selected.parts||[]),...(selected.decals||[])];if(selectedPart&&!parts.includes(selectedPart))selectedPart=null;parts.forEach((p,i)=>{let d=document.createElement('div');d.className='item';d.textContent=`${p.kind==='bar'?'Vara':p.kind==='panel'?'Panel':'Logo'} ${i+1}`;d.onclick=()=>{selectedPart=p;renderComponentControls();status('Componente seleccionado')};box.appendChild(d)})}
let selectedPart=null;const originalUpdateUI=updateUI;updateUI=function(){originalUpdateUI();renderObstacleComponents()};
const originalActiveLogo=activeLogo;activeLogo=function(){return selectedPart?.kind==='logo'?selectedPart:originalActiveLogo()};
$('#partColor').oninput=e=>{if(selectedPart&&selectedPart.kind!=='logo'){history();selectedPart.color=e.target.value;draw()}};$('#partMaterial').onchange=e=>{if(selectedPart&&selectedPart.kind!=='logo'){history();selectedPart.material=e.target.value;draw()}};
function renderComponentControls(){let inspector=$('#inspector');if(!inspector)return;let box=$('#componentActions');if(!box){box=document.createElement('div');box.id='componentActions';box.className='card';inspector.appendChild(box)}if(!selectedPart){box.style.display='none';return}box.style.display='block';let isLogo=selectedPart.kind==='logo';box.innerHTML=`<strong>Componente seleccionado</strong><div class="row" style="margin-top:8px"><button class="btn" id="duplicateComponent">Duplicar</button><button class="btn danger" id="deleteComponent">Eliminar</button></div>${isLogo?'':'<div class="grid2" style="margin-top:8px"><div class="field"><label>Altura / Z</label><input id="componentZ" type="number" step=".05" value="'+(selectedPart.z||0)+'"></div><div class="field"><label>Ancho relativo</label><input id="componentWidth" type="number" min=".1" max="2" step=".05" value="'+(selectedPart.width||1)+'"></div></div>'+(selectedPart.kind==='panel'?'<div class="field"><label>Alto del panel</label><input id="componentHeight" type="number" min=".1" max="5" step=".05" value="'+(selectedPart.height||1)+'"></div>':'')}`;$('#duplicateComponent').onclick=()=>{if(!selected||!selectedPart)return;history();let copy=JSON.parse(JSON.stringify(selectedPart));copy.id=uid();if(copy.kind==='logo')copy.offsetX=(copy.offsetX||0)+.12;else copy.z=(copy.z||0)+.25;let key=copy.kind==='logo'?'decals':'parts';selected[key]=selected[key]||[];selected[key].push(copy);selectedPart=copy;updateUI();draw();status('Componente duplicado')};$('#deleteComponent').onclick=()=>{if(!selected||!selectedPart)return;history();let key=selectedPart.kind==='logo'?'decals':'parts';selected[key]=(selected[key]||[]).filter(p=>p!==selectedPart);selectedPart=null;updateUI();draw();status('Componente eliminado')};if(!isLogo){$('#componentZ').oninput=e=>{history();selectedPart.z=+e.target.value;draw()};$('#componentWidth').oninput=e=>{history();selectedPart.width=+e.target.value;draw()};if(selectedPart.kind==='panel')$('#componentHeight').oninput=e=>{history();selectedPart.height=+e.target.value;draw()}}}
const updateUIWithComponents=updateUI;updateUI=function(){updateUIWithComponents();renderComponentControls()};
function ensureComponentPalette(){let inspector=$('#inspector');if(!inspector)return;let box=$('#componentPalette');if(!box){box=document.createElement('div');box.id='componentPalette';box.className='card';box.innerHTML='<strong>Añadir elemento</strong><div class="row" style="margin-top:8px"><button class="btn" id="addPlank">Tablón</button><button class="btn" id="addDoor">Puerta</button></div><div class="row" style="margin-top:8px"><button class="btn" id="addFiller">Relleno</button><button class="btn" id="addWall">Muro</button></div><div class="row" style="margin-top:8px"><button class="btn" id="addSupport">Soporte</button><button class="btn" id="addRail">Riel</button></div><button class="btn" id="addDecor" style="width:100%;margin-top:8px">Decoración</button>';inspector.appendChild(box);box.querySelector('#addPlank').onclick=()=>obstaclePart('plank');box.querySelector('#addDoor').onclick=()=>obstaclePart('door');box.querySelector('#addFiller').onclick=()=>obstaclePart('filler');box.querySelector('#addWall').onclick=()=>obstaclePart('wall');box.querySelector('#addSupport').onclick=()=>obstaclePart('support');box.querySelector('#addRail').onclick=()=>obstaclePart('rail');box.querySelector('#addDecor').onclick=()=>obstaclePart('decor')}box.style.display=selected?'block':'none'}
const updateUIWithPalette=updateUI;updateUI=function(){updateUIWithPalette();ensureComponentPalette()};
function renderSceneRefs(){let left=$('#leftPanel');if(!left)return;let box=$('#sceneReferenceCard');if(!box){box=document.createElement('div');box.id='sceneReferenceCard';box.className='card';box.innerHTML='<strong>Referencias de escenario</strong><p class="tiny">Ambientes y escenarios reservados para la futura escena 3D.</p><div id="sceneReferenceList" class="list"></div>';left.appendChild(box)}let list=$('#sceneReferenceList');if(!list)return;list.innerHTML='';sceneRefs.forEach((r,i)=>{let d=document.createElement('div');d.className='item';d.innerHTML=`<span>${r.name}</span><button class="btn" data-place-index="${i}">Colocar</button><button class="btn danger" data-scene-index="${i}">×</button>`;d.querySelector('[data-place-index]').onclick=()=>placeSceneReference(r);d.querySelector('[data-scene-index]').onclick=()=>{history();sceneRefs.splice(i,1);updateUI();status('Referencia de escenario eliminada')};list.appendChild(d)})}
function placeSceneReference(ref){let cat=(ref.category||'').toLowerCase(),dimensions=cat.includes('ambiente')?{width:3,depth:3,height:8}:cat.includes('escenario')?{width:14,depth:5,height:4}:{width:6,depth:3,height:1.2};history();sceneObjects.push({id:uid(),assetId:ref.assetId,name:ref.name,category:ref.category,src:ref.src,x:W/2,y:H/2,scale:1,rotation:0,dimensions});updateUI();draw();status('Referencia colocada en la pista')}
function drawSceneObjects(){sceneObjects.forEach(o=>{if(!logoImages[o.id]&&typeof Image!=='undefined'){let image=new Image();image.onload=draw;image.src=o.src;logoImages[o.id]=image}let image=logoImages[o.id];if(!image||!image.complete)return;let p=project(o.x,o.y,.02),size=70*(o.scale||1);ctx.save();ctx.globalAlpha=.55;ctx.translate(p.x,p.y);ctx.rotate((o.rotation||0)*Math.PI/180);ctx.drawImage(image,-size/2,-size/2,size,size);ctx.restore()})}
const baseSceneDraw=draw;draw=function(){baseSceneDraw();drawSceneObjects()};
const updateUIWithScenes=updateUI;updateUI=function(){updateUIWithScenes();renderSceneRefs()};
async function deliverExport(blob,name,mime){if(!blob)return false;let file=new File([blob],name,{type:mime});if(typeof navigator!=='undefined'&&navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:name});return true}catch(e){if(e?.name==='AbortError')return false}}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return true}
$('#saveBtn').onclick=()=>{let data={version:'0.7',arena:{width:W,length:H},objects,assets,sceneRefs,sceneObjects,route};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='faas_equestrian_course.json';a.click();URL.revokeObjectURL(a.href);status('Proyecto guardado')};
$('#fileInput').onchange=async e=>{try{let data=JSON.parse(await e.target.files[0].text());objects=data.objects||[];assets=data.assets||[];sceneRefs=data.sceneRefs||[];sceneObjects=data.sceneObjects||[];route=(data.route||[]).map(n=>typeof n==='string'?{id:uid(),kind:'obstacle',objectId:n,x:objects.find(o=>o.id===n)?.x||0,y:objects.find(o=>o.id===n)?.y||0}:n);W=data.arena?.width||80;H=data.arena?.length||60;$('#arenaW').value=W;$('#arenaH').value=H;selected=null;updateUI();draw();status('Proyecto abierto')}catch{status('No se pudo abrir el JSON')}};
function sceneBox(x,y,w,d,h,color){let a=project(x-w/2,y-d/2,0),b=project(x+w/2,y-d/2,0),c=project(x+w/2,y+d/2,0),e=project(x-w/2,y+d/2,0),at=project(x-w/2,y-d/2,h),bt=project(x+w/2,y-d/2,h),ct=project(x+w/2,y+d/2,h),et=project(x-w/2,y+d/2,h);ctx.save();ctx.fillStyle=color;ctx.strokeStyle='#07111f99';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(at.x,at.y);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(ct.x,ct.y);ctx.lineTo(bt.x,bt.y);ctx.closePath();ctx.fillStyle=color+'cc';ctx.fill();ctx.beginPath();ctx.moveTo(at.x,at.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(ct.x,ct.y);ctx.lineTo(et.x,et.y);ctx.closePath();ctx.fillStyle=color+'ee';ctx.fill();ctx.restore()}
drawSceneObjects=function(){sceneObjects.forEach(o=>{let s=o.scale||1,cat=(o.category||'').toLowerCase();if(cat.includes('ambiente')){sceneBox(o.x,o.y,3*s,3*s,8*s,'#6b432f',o.rotation||0);let p=project(o.x,o.y,10*s);ctx.save();ctx.fillStyle='#3d9b5b';ctx.beginPath();ctx.arc(p.x,p.y,18*s,0,Math.PI*2);ctx.fill();ctx.restore()}else if(cat.includes('escenario')){sceneBox(o.x,o.y,14*s,5*s,2*s,'#65748b',o.rotation||0);sceneBox(o.x,o.y-2*s,12*s,3*s,3*s,'#7d8da3',o.rotation||0);sceneBox(o.x,o.y-3.5*s,10*s,2*s,4*s,'#9ba8b9',o.rotation||0)}else{sceneBox(o.x,o.y,6*s,3*s,1.2*s,'#b07a4d',o.rotation||0)}if(o.src&&typeof Image!=='undefined'){if(!logoImages[o.id]){let image=new Image();image.onload=draw;image.src=o.src;logoImages[o.id]=image}let image=logoImages[o.id];if(image&&image.complete){let p=project(o.x,o.y,1.3*s),size=35*s;ctx.save();ctx.globalAlpha=.8;ctx.drawImage(image,p.x-size/2,p.y-size/2,size,size);ctx.restore()}}})};
function hitSceneObject(sx,sy){for(let i=sceneObjects.length-1;i>=0;i--){let o=sceneObjects[i],p=project(o.x,o.y,.5),size=42*(o.scale||1);if(Math.hypot(sx-p.x,sy-p.y)<size)return o}return null}
canvas.addEventListener('pointerdown',e=>{if(placeType||routeMode||connectMode)return;let q=pointerPos(e),o=hitSceneObject(q.x,q.y);if(!o)return;e.stopImmediatePropagation();canvas.setPointerCapture(e.pointerId);selectedScene=o;sceneDrag={o,before:snapshot(),start:unproject(q.x,q.y),x:o.x,y:o.y};updateUI();status('Elemento de escenario seleccionado');draw()},true);
canvas.addEventListener('pointermove',e=>{if(!sceneDrag)return;e.stopImmediatePropagation();let q=pointerPos(e),p=unproject(q.x,q.y);sceneDrag.o.x=Math.max(0,Math.min(W,p.x));sceneDrag.o.y=Math.max(0,Math.min(H,p.y));draw()},true);
canvas.addEventListener('pointerup',e=>{if(!sceneDrag)return;e.stopImmediatePropagation();past.push(sceneDrag.before);if(past.length>MAX_HISTORY)past.shift();future=[];buttons();sceneDrag=null;draw()},true);
sceneBox=function(x,y,w,d,h,color,rotation=0){let r=rotation*Math.PI/180,point=(dx,dy,z)=>project(x+dx*Math.cos(r)-dy*Math.sin(r),y+dx*Math.sin(r)+dy*Math.cos(r),z),a=point(-w/2,-d/2,0),b=point(w/2,-d/2,0),c=point(w/2,d/2,0),e=point(-w/2,d/2,0),at=point(-w/2,-d/2,h),bt=point(w/2,-d/2,h),ct=point(w/2,d/2,h),et=point(-w/2,d/2,h);ctx.save();ctx.fillStyle=color;ctx.strokeStyle='#07111f99';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(at.x,at.y);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(c.x,c.y);ctx.lineTo(ct.x,ct.y);ctx.lineTo(bt.x,bt.y);ctx.closePath();ctx.fillStyle=color+'cc';ctx.fill();ctx.beginPath();ctx.moveTo(at.x,at.y);ctx.lineTo(bt.x,bt.y);ctx.lineTo(ct.x,ct.y);ctx.lineTo(et.x,et.y);ctx.closePath();ctx.fillStyle=color+'ee';ctx.fill();ctx.restore()};
function renderSceneControls(){let panel=$('#rightPanel');if(!panel)return;let box=$('#sceneControls');if(!box){box=document.createElement('div');box.id='sceneControls';box.className='card';panel.insertBefore(box,panel.firstChild)}if(!selectedScene){box.style.display='none';return}box.style.display='block';box.innerHTML=`<strong>Elemento de escenario</strong><p class="tiny">${selectedScene.name||'Referencia 3D'}</p><div class="field"><label>Escala</label><input id="sceneScale" type="range" min=".25" max="4" step=".05" value="${selectedScene.scale||1}"></div><div class="field"><label>Rotación °</label><input id="sceneRotation" type="range" min="-180" max="180" value="${selectedScene.rotation||0}"></div><button class="btn danger" id="deleteSceneObject" style="width:100%">Eliminar elemento</button>`;$('#sceneScale').oninput=e=>{history();selectedScene.scale=+e.target.value;draw()};$('#sceneRotation').oninput=e=>{history();selectedScene.rotation=+e.target.value;draw()};$('#deleteSceneObject').onclick=()=>{history();sceneObjects=sceneObjects.filter(o=>o!==selectedScene);selectedScene=null;updateUI();draw();status('Elemento de escenario eliminado')}}
const updateUIWithSceneControls=updateUI;updateUI=function(){updateUIWithSceneControls();renderSceneControls()};
renderSceneControls=function(){let panel=$('#rightPanel');if(!panel)return;let box=$('#sceneControls');if(!box){box=document.createElement('div');box.id='sceneControls';box.className='card';panel.insertBefore(box,panel.firstChild)}if(!selectedScene){box.style.display='none';return}let d=selectedScene.dimensions||{width:6,depth:3,height:1.2};box.style.display='block';box.innerHTML=`<strong>Elemento de escenario</strong><p class="tiny">${selectedScene.name||'Referencia 3D'}</p><div class="grid2"><div class="field"><label>Ancho m</label><input id="sceneWidth" type="number" min=".5" step=".1" value="${d.width}"></div><div class="field"><label>Profundidad m</label><input id="sceneDepth" type="number" min=".5" step=".1" value="${d.depth}"></div></div><div class="field"><label>Altura m</label><input id="sceneHeight" type="number" min=".5" step=".1" value="${d.height}"></div><div class="field"><label>Escala</label><input id="sceneScale" type="range" min=".25" max="4" step=".05" value="${selectedScene.scale||1}"></div><div class="field"><label>Rotación °</label><input id="sceneRotation" type="range" min="-180" max="180" value="${selectedScene.rotation||0}"></div><div class="row"><button class="btn" id="duplicateSceneObject">Duplicar</button><button class="btn danger" id="deleteSceneObject">Eliminar</button></div>`;['sceneWidth','sceneDepth','sceneHeight'].forEach((id,i)=>$('#'+id).oninput=e=>{history();selectedScene.dimensions=selectedScene.dimensions||{};selectedScene.dimensions[['width','depth','height'][i]]=Math.max(.5,+e.target.value);draw()});$('#sceneScale').oninput=e=>{history();selectedScene.scale=+e.target.value;draw()};$('#sceneRotation').oninput=e=>{history();selectedScene.rotation=+e.target.value;draw()};$('#duplicateSceneObject').onclick=()=>{history();let copy=JSON.parse(JSON.stringify(selectedScene));copy.id=uid();copy.x=Math.min(W,copy.x+5);copy.y=Math.min(H,copy.y+5);sceneObjects.push(copy);selectedScene=copy;updateUI();draw();status('Elemento de escenario duplicado')};$('#deleteSceneObject').onclick=()=>{history();sceneObjects=sceneObjects.filter(o=>o!==selectedScene);selectedScene=null;updateUI();draw();status('Elemento de escenario eliminado')}};
drawSceneObjects=function(){sceneObjects.forEach(o=>{let s=o.scale||1,cat=(o.category||'').toLowerCase(),d=o.dimensions||{},base=cat.includes('ambiente')?{width:3,depth:3,height:8}:cat.includes('escenario')?{width:14,depth:5,height:4}:{width:6,depth:3,height:1.2},w=(d.width||base.width)*s,dep=(d.depth||base.depth)*s,h=(d.height||base.height)*s;if(cat.includes('ambiente')){sceneBox(o.x,o.y,w,dep,h,'#6b432f',o.rotation||0);let p=project(o.x,o.y,h);ctx.save();ctx.fillStyle='#3d9b5b';ctx.beginPath();ctx.arc(p.x,p.y,18*s,0,Math.PI*2);ctx.fill();ctx.restore()}else if(cat.includes('escenario')){sceneBox(o.x,o.y,w,dep,h*.5,'#65748b',o.rotation||0);sceneBox(o.x,o.y-2*s,w*.85,dep*.6,h*.75,'#7d8da3',o.rotation||0)}else sceneBox(o.x,o.y,w,dep,h,'#b07a4d',o.rotation||0);if(o.src&&typeof Image!=='undefined'){if(!logoImages[o.id]){let image=new Image();image.onload=draw;image.src=o.src;logoImages[o.id]=image}let image=logoImages[o.id];if(image&&image.complete){let p=project(o.x,o.y,h*.75),size=Math.max(25,35*s);ctx.save();ctx.globalAlpha=.8;ctx.drawImage(image,p.x-size/2,p.y-size/2,size,size);ctx.restore()}}})};
renderAssets=function(){let box=$('#assetList');if(!box)return;box.innerHTML='';assets.forEach((a,i)=>{let d=document.createElement('div');d.className='item asset-item';d.title='Toca la referencia para aplicarla';d.innerHTML=`<img src="${a.src}" alt="" class="asset-thumb"><span><b>${a.name}</b><br><small>${a.category}${a.description?' · '+a.description:''}</small></span><button class="btn danger" title="Eliminar referencia">×</button>`;d.querySelector('button').onclick=e=>{e.stopPropagation();history();assets.splice(i,1);updateUI();status('Referencia eliminada')};d.onclick=()=>applyReferenceAsset(a);box.appendChild(d)})};
$('#saveBtn').onclick=async()=>{let data={version:'0.7',arena:{width:W,length:H},objects,assets,sceneRefs,sceneObjects,route},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});if(await deliverExport(blob,'faas_equestrian_course.json','application/json'))status('Proyecto guardado o compartido')};
$('#exportPng').onclick=()=>{draw();canvas.toBlob(async blob=>{let stamp=new Date().toISOString().slice(0,10);if(await deliverExport(blob,`faas_equestrian_course_${stamp}.png`,'image/png'))status('Diseño PNG guardado o compartido')},'image/png')};
let recordingExecution=false;
$('#recordExecution').onclick=async()=>{if(recordingExecution||executionRunning){status('La ejecución ya está en marcha');return}if(!canvas.captureStream||typeof MediaRecorder==='undefined'){status('Este Safari no permite grabar video desde la pista');return}let queue=buildExecutionQueue();if(!queue.length){status('Define un recorrido o una línea antes de grabar');return}let stream=canvas.captureStream(30),types=['video/mp4;codecs=avc1.42E01E','video/mp4','video/webm;codecs=vp9','video/webm'],mime=types.find(t=>MediaRecorder.isTypeSupported?.(t))||'';let recorder;try{recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined)}catch{stream.getTracks().forEach(t=>t.stop());status('No se pudo iniciar la grabación');return}let chunks=[];recordingExecution=true;let button=$('#recordExecution');button.disabled=true;button.textContent='Grabando ejecución…';recorder.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data)};recorder.onstop=async()=>{let type=recorder.mimeType||mime||'video/webm',ext=type.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type});stream.getTracks().forEach(t=>t.stop());recordingExecution=false;button.disabled=false;button.textContent='Grabar ejecución como video';if(await deliverExport(blob,`faas_equestrian_execution_${new Date().toISOString().slice(0,10)}.${ext}`,type))status('Video guardado o compartido')};recorder.start();startExecution();let watch=setInterval(()=>{if(!executionRunning){clearInterval(watch);recorder.stop()}},100)};
const baseRouteLabel=routeLabel;routeLabel=n=>n.kind==='courseControl'?'Punto verde del recorrido':baseRouteLabel(n);
function moveRouteEntry(index,delta){let target=index+delta;if(index<0||target<0||target>=route.length)return;history();[route[index],route[target]]=[route[target],route[index]];routeSelection=route[target];selected=null;updateUI();draw();status('Orden del recorrido actualizado')}
function renderEnhancedRouteList(){let box=$('#routeList');if(!box)return;box.innerHTML='';route.forEach((n,i)=>{let d=document.createElement('div');d.className='item';d.dataset.routeIndex=i;let label=document.createElement('span');label.className='route-entry-label';label.textContent=routeLabel(n);let badge=document.createElement('span');badge.className='badge';badge.textContent=i+1;let actions=document.createElement('span');actions.className='route-entry-actions';let up=document.createElement('button'),down=document.createElement('button');up.className='btn route-order-btn';down.className='btn route-order-btn';up.textContent='↑';down.textContent='↓';up.title='Subir elemento';down.title='Bajar elemento';up.disabled=i===0;down.disabled=i===route.length-1;up.onclick=e=>{e.stopPropagation();moveRouteEntry(i,-1)};down.onclick=e=>{e.stopPropagation();moveRouteEntry(i,1)};actions.append(up,down);d.append(badge,label,actions);d.onclick=()=>{routeSelection=n;selected=null;updateUI();draw()};if(n===routeSelection)d.classList.add('active');box.appendChild(d)})}
const updateUIWithEnhancedRoute=updateUI;updateUI=function(){updateUIWithEnhancedRoute();renderEnhancedRouteList()};
autoOrder=function(){let nodes=courseObstacleNodes(),links=route.filter(n=>n.kind==='connection'&&n.fromObstacleId&&n.toObstacleId);if(nodes.length<2){status('Añade al menos 2 obstáculos al recorrido');return}let start=route.find(n=>n.kind==='point'&&n.marker==='start'),finish=route.find(n=>n.kind==='point'&&n.marker==='finish'),near=p=>nodes.slice().sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0],cur=start?near(start):nodes[0],ordered=[],used=new Set;while(cur&&!used.has(cur.objectId)){ordered.push(cur);used.add(cur.objectId);let l=links.find(n=>n.fromObstacleId===cur.objectId&&!used.has(n.toObstacleId));cur=l?nodes.find(n=>n.objectId===l.toObstacleId):null}nodes.filter(n=>!used.has(n.objectId)).forEach(n=>ordered.push(n));let course=[];ordered.forEach((n,i)=>{course.push(n);let next=ordered[i+1],l=next&&links.find(x=>x.fromObstacleId===n.objectId&&x.toObstacleId===next.objectId);if(l)course.push(l)});if(start)course.unshift(start);if(finish)course.push(finish);let extras=route.filter(n=>!['obstacle','connection','point'].includes(n.kind));history();route=[...course,...extras];ordered.forEach((n,i)=>{let o=objects.find(x=>x.id===n.objectId);if(o&&!o.manualNum)o.num=String(i+1)});routeSelection=null;updateUI();draw();status('Recorrido ordenado; puntos verdes conservados')};
// Ejecución final: respeta el orden existente y no vuelve a preguntar al usuario.
startExecution=function(){let items=[];if(allRoutePoints().length>1)items.push({kind:'courseRun',id:'course',color:executionColor,width:executionWidth,dash:executionDash});route.filter(n=>['line','curve','connection','circle'].includes(n.kind)).forEach(n=>items.push(n));if(!items.length){status('No hay líneas ni recorrido para ejecutar');return}executionQueue=items;executionIndex=0;executionProgress=0;executionRunning=true;anim=false;$('#play').textContent='⏸ Pausar';status('Ejecución iniciada en el orden de producción')};
drawExecutionOverlay=function(){let n=executionQueue[executionIndex];if(!n)return;let shape=n.kind==='courseRun'?catmull(allRoutePoints(),18):n.kind==='line'?nodePoints(n):n.kind==='circle'?nodePoints(n):catmull(nodePoints(n),18);if(shape.length<2)return;let count=Math.max(2,Math.ceil(shape.length*executionProgress)),pts=shape.slice(0,count).map(p=>project(p.x,p.y,.18));ctx.save();ctx.strokeStyle=executionColor;ctx.lineWidth=executionWidth;ctx.setLineDash(executionDash==='dashed'?[12,9]:executionDash==='dotted'?[3,8]:[]);ctx.shadowColor=executionColor;ctx.shadowBlur=10;ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.restore();if(pts.length>1)arrow(shape[count-2],shape[count-1],executionColor)};
})();
